export { default as InputCCCD } from './InputCCCD'
export { default as InputDate } from './InputDate'
export * from './InputForm'
export { default as InputImage } from './InputImage'
export { default as InputRadio } from './InputRadio'
export { default as InputSelect } from './InputSelect'
export { InputMask, InputRows, InputText } from './InputText'
export { default as InputTitle } from './InputTitle'
export * from './InputTitle'
export * from './styleInput'