export const EN = {
  ai_do: `Someone`,
  an: `Hide`,
  anh_chi_em: `Brother or sister`,
  anh_CMND: `Identity card`,
  anh_dang_ky_xe: `Vehicle registration picture`,
  bac: `Step`,
  ban_chua_nhap_du: `You have not entered data`,
  ban_muon_chia_se: `What do you think`,
  bang_chu: `In words`,
  bang_ke_dv_thang: `Listing of services in 6/2022`,
  bang_tin: `News`,
  bi_danh: `Name`,
  bien_so_xe: `License plate`,
  biet_do_tien_nuoc: `Water money chart`,
  bieu_do_so_dien: `Chart of electricity report `,
  bieu_do_so_nuoc: `Chart of water report`,
  bieu_do_tien_dien: `Electricity bill chart`,
  bieu_do_tong_ps_thang: `Total of arising in a month chart `,
  binh_luan: `Comment`,
  bo_me: `Parent `,
  bo_phan_tiep_nhan: `The dossier-receiving department`,
  bo_qua: `Skip`,
  bql: `Board of building management`,
  bql_viet_tat: `BBM`,
  buon: `Sad`,
  cac_dich_vu: `Services`,
  cai_dat_thanh_cong: `Successful installation`,
  can_cho_phep_sd_cam: `You need to allow the app to use the camera`,
  can_ho: `Apartment`,
  can_ho_khac: `Other apartment`,
  can_su_dung_bo_nho: `You need to allow the app to use memory.`,
  can_thanh_toan: `Need to pay amount`,
  cap_nhat_sau_khi_tai: `The application will be updated after the download is completed`,
  cap_nhat_tt_ca_nhan: `Update personal information`,
  chao: `Hi`,
  chi_nhanh: `Branch`,
  chi_so_cuoi: `New figure`,
  chi_so_dau: `Old figure`,
  chi_tiet: `Detail`,
  chi_tiet_phieu: `Details`,
  chi_tiet_y_kien: `Comment details`,
  cho_phan_hoi: `Awaiting`,
  cho_phep_may_anh: `You need to allow the app to use the camera`,
  cho_phep_micro: `You need to allow the app to use the micro`,
  chon: `Seclect`,
  chon_anh_bien_so_xe: `Please choose a photo of the license plate`,
  chon_anh_cmnd: `Please choose photo of ID`,
  chon_anh_dk_xe: `Please select vehicle registration photo`,
  chon_bo_phan_tiep_nhan: `Select the receiving department`,
  chon_loai_thanh_toan: `Please choose a services for paying`,
  chon_loai_xe: `Please select vehicle type`,
  chon_ngay_huy_xe: `Please select the start date of cancellation`,
  chon_pt_thanh_toan: `Choose payment method`,
  chon_xe: `Select vehicle`,
  chong: `Husband`,
  chu_ho: `Host`,
  chu_ho_cu: `Old host`,
  chu_phuong_tien: `Vehicle owner`,
  chu_tai_khoan: `Owner Account`,
  chu_y_chuyen_khoan: `Opening Banking, transfering with number of account and content of transfering to finish your payment`,
  chu_y_tai_video: `Download only one video and the total capacity is less than 50MB`,
  chu_y_thanh_toan: `Mimimum payment 10,000 VND`,
  chu_y_thanh_toan1: `Note: After scan QR code, please check exactly receiving account as well as the owner name account `,
  chu_y_thanh_toan2: `Put in exactly content of transfering to pay all services you selected, the preference services will be selected in case of your transfering content not correct`,
  chua_su_dung_dich_vu: `You have not used this service yet`,
  chua_thanh_toan: `Unpaid`,
  chua_thanh_toan_du: `Outstanding expense`,
  chuyen_khoan_9pay: `Bank transfer with 9pay`,
  chuyen_khoan_viqr: `Transfering with Viet-QR`,
  co: `Yes`,
  con_cai: `Children`,
  con_lai: `Rest`,
  con_no: `Liability`,
  cong_dong: `Community`,
  da_cap_nhat: `Updated successfully.`,
  da_cap_nhat_y_kien: `Feedback updated`,
  da_gui: `Sent`,
  da_hoan_thanh: `Completed`,
  da_huy: `Canceled`,
  da_ket_thuc: `Finished`,
  da_luu_bo_nho: `Cached`,
  da_qua_han: `Overdue`,
  da_thanh_toan: `Payment received `,
  da_them_y_kien: `Added feedback`,
  da_tiep_nhan: `Received `,
  da_xoa_bai_viet: `You deleted the post`,
  dang_bai: `Post`,
  dang_cai_dat: `Installing `,
  dang_cap_nhat: `The application is updating data`,
  dang_dien_ra: `Happenning `,
  dang_ky_tham_gia: `Register `,
  dang_ky_thanh_cong: `You have successfully registered`,
  dang_ky_xe: `Register `,
  dang_nhap: `Log in`,
  dang_tai: `Loading...`,
  dang_xu_ly: `Processing...`,
  dang_xuat: `Sign out`,
  danh_gia: `Rate`,
  danh_gia_bql: `Management Service Quality`,
  danh_gia_dich_vu: `Service quality rating`,
  danh_muc: `Category`,
  danh_muc_noi_quy: `List of regulations`,
  danh_muc_tien_ich: `List of utilitities`,
  danh_sach_phi: `Listing of fees`,
  danh_sach_thanh_vien: `Members`,
  danh_sach_xe: `Listing of vehicles`,
  danh_sach_yeu_cau: `Listing of requirements`,
  dat_lai_mat_khau: `Reset password`,
  den: `To`,
  dia_chi: `Address`,
  dia_diem_dong: `Pay fee place`,
  dich_vu: `Services `,
  dich_vu_dien: `Eclectricity services `,
  dich_vu_nuoc: `Your water use`,
  dich_vu_phuong_tien: `Vehicles services `,
  dien_ma_code: `Please input 6 characters from your message`,
  dien_tich: `Area`,
  dinh_kem: `Attach file`,
  doi_can_ho: `Change apartment `,
  don_gia: `Unit price`,
  don_vi: `Unit`,
  dong: `Close`,
  dong_y: `Agree`,
  du_cu: `Surplus amount`,
  dv_tien: `VND`,
  dv_tien_thu_gon: `VND`,
  email: `Email`,
  email_sdt_sai_dinh_dang: `Email/ phone invalidate`,
  gan_day_12_thang: `The last 12 months`,
  gan_day_3_nam: `3 recent years`,
  gan_day_6_thang: `The last 6 months`,
  ghi_chu: `Note`,
  giam_tru: `Discount`,
  giao_dich_gan_day: `Recently transaction`,
  giay: `Sections`,
  gio: `Time`,
  gioi_tinh: `Sex`,
  gioi_tinh_nam: `Male`,
  gioi_tinh_nu: `Female`,
  gui: `Send `,
  gui_ngay: `Send now`,
  gui_phieu_dk_thanh_cong: `Successfully submitted registration form`,
  gui_y_kien: `Send`,
  gui_yeu_cau_thanh_cong: `Submit request form successfully`,
  haha: `Haha`,
  han: `Due date`,
  hd_chup_bien_so: `Vehicle photo (requires a clear photo of license plate)`,
  hd_thanh_toan1: `Opening Banking`,
  hd_thanh_toan2: `Transfering with number of account and content of transfering to finish your payment`,
  he_thong_nhan_tien: `The system has recorded your amount as `,
  hinh_anh: `Photos`,
  hinh_thuc: `Form`,
  ho_ten: `Full name`,
  ho_tro: `Support`,
  hoa_don: `Invoice`,
  hoac: `Or`,
  hoi_dang_xuat: `Do you want to sign out`,
  hom_nay: `Today`,
  ht_phan_hoi_lau: `The system responds for a long time, please try again later`,
  huy: `Cancel`,
  huy_dang_ky: `Cancel `,
  huy_dang_ky_thanh_cong: `You have successfully unsubscribed`,
  huy_dich_vu: `Cancel the services`,
  huy_tham_gia: `Cancel`,
  khac: `Other`,
  khach_thue: `Tenants`,
  khong: `N/A`,
  khong_co_bang_tin: `No newfeed`,
  khong_co_du_lieu: `No data`,
  khong_co_hoa_don: `No invoice`,
  khong_co_nha: `Your account dont belong to any flat, please contact to the management board for supporting `,
  khong_co_noi_dung: `No content`,
  khong_co_phieu_thu: `No receipt `,
  khong_co_su_kien: `No event`,
  khong_co_thong_bao: `No notice`,
  khong_co_tin_moi: `No news`,
  khong_co_y_kien_dg: `No comment `,
  khong_dang_ky_duoc: `Unable to register`,
  khong_hien_thi: `Don't show`,
  khong_huy_dang_ky_duoc: `Can't unsubscribe`,
  khong_mo_file_duoc: `Unable to open file`,
  khong_su_dung_dv: `Don't use services in this period time`,
  khong_tai_file_duoc: `Unable to download file`,
  khong_thanh_cong: `Unsuccessful`,
  ky_tu: `Characters`,
  lich_su_giao_dich: `Transaction history`,
  lich_su_thanh_toan: `Payment History`,
  lien_ket: `Link`,
  loai_xe: `Type of vehicles `,
  loi_ket_noi: `Connection errors`,
  luc: `At`,
  luu: `Save`,
  luu_lai: `Save`,
  ly_do: `Reason `,
  ma_can_ho: `Flat code`,
  ma_code_6_kt: `Code must be 6 characters`,
  ma_code_chua_nhap: `Code has not been entered`,
  ma_loi: `Error code`,
  mat_khau: `Pass `,
  mat_khau_khong_khop: `Password incorrect`,
  mat_khau_sai_dinh_dang: `Invalid password, minimun 6 characters`,
  may_chu_loi: `The server is error, please try again later`,
  mo_ta: `Description `,
  mo_ta_can_ho: `Apartment Description`,
  mo_ta_y_kien_danh_gia: `Our services will be improved by your appreciation `,
  nam_nay: `This year`,
  nang_cap_ung_dung: `Update App`,
  ngan_hang: `Bank `,
  ngay: `Date`,
  ngay_bat_dau_sd: `Expected start date`,
  ngay_cap: `Date issue`,
  ngay_du_kien_huy: `Expected date of cancellation`,
  ngay_ket_thuc_sd: `Expected end-of-use date`,
  ngay_sinh: `Date of birth`,
  ngay_tham_gia: `Join Date`,
  ngay_thanh_toan: `Date of payment`,
  ngon_ngu: `Language`,
  nguoi_nop: `Payer`,
  nguoi_trong_can_ho: `List of members`,
  nhan_otp: `Issue OTP `,
  nhap_bien_so_xe: `Please enter license plate number`,
  nhap_ly_do: `Please enter a reason for the request`,
  nhap_ma_tai_day: `Input OTP here`,
  nhap_mail_sdt: `Log in (Phone/Email)`,
  nhap_mat_khau: `Password`,
  nhap_mk_hien_tai: `Current password`,
  nhap_mk_moi: `New password`,
  nhap_ngay: `Input the date`,
  nhap_ngay_bat_dau: `Please enter the date of starting`,
  nhap_noi_dung: `Input content`,
  nhap_tai_day: `Input here`,
  nhap_tieu_de_noi_dung: `You need to enter the full title/content`,
  no_cu: `Old debit`,
  noi_cap: `Issue by`,
  noi_dung: `Content`,
  noi_dung_chuyen_khoan: `Content of transfering `,
  noi_dung_thanh_toan: `Payment content`,
  noi_quy: `Regulations`,
  o_to: `Car`,
  phan_no: `Angry`,
  phat_sinh_thang: `Monthly arising`,
  phat_sinh_trong_ky: `Arising in this month `,
  phi_dich_vu: `Services Fee`,
  phi_dien: `Electricity fee`,
  phi_khac: `Other fee`,
  phi_nuoc: `Water fee`,
  phi_phuong_tien: `Vehicle fee`,
  phi_thang: `Management fee`,
  phien_ban_moi_nhat: `The current version is the latest`,
  phieu_thu: `Receipts`,
  phieu_yeu_cau: `Request form`,
  phut: `Minutes`,
  qua_han_va_con_no: `Overdue debt`,
  quan_he_chu_ho: `Relationship with the host`,
  quay_lai: `Back`,
  quen: `Forget`,
  quen_mat_khau: `Forget Password`,
  quet_qr: `Scan QRCode`,
  quet_qr_chuyen_khoan: `Scan QR code to transfer`,
  quet_qr_danh_gia: `Scan QR-code to rate the service`,
  sai_dinh_dang: `Wrong format`,
  sdt: `Tel`,
  sdt_khan_cap: `Hotline`,
  se_tham_gia: `Join`,
  so: `No`,
  so_bang_ke: `Number of bill`,
  so_CMND: `Indentify`,
  so_du: `Balance`,
  so_du_can_ho: `Apartment balance`,
  so_tai_khoan: `Number of Bank Account `,
  so_tien_bang_chu: `Amount in words`,
  so_tien_nop: `Amount of money`,
  so_tk_nhan: `Receiving account number`,
  su_kien: `Event `,
  su_kien_ket_thuc: `Event was finished `,
  sua: `Edit`,
  sua_bai_viet: `Edit post`,
  sua_y_kien: `Edit comment`,
  tai_day: `Here`,
  tai_khoan_nhan_thanh_toan: `Account of receiver `,
  tai_xuong: `Download `,
  tang: `Floor`,
  tat_ca: `All`,
  tat_ca_anh_video: `All photos/video`,
  tat_ca_hoa_don: `All invoice`,
  tat_ca_no: `Total of debt `,
  ten_can_ho: `Name of flat`,
  ten_chu_ho: `Host`,
  ten_chu_khoan: `Account holder's name`,
  ten_dich_vu: `Service name`,
  ten_ngan_hang: `Bank name`,
  thac_mac_lien_he: `Please contact to BBM when have any questions`,
  thang: `Month`,
  thanh_cong: `Succes`,
  thanh_tien: `Total`,
  thanh_toan: `Payment `,
  thanh_toan_chua_du: `Outstanding expense`,
  thanh_toan_chuyen_khoan: `Transfer`,
  thanh_toan_ngay: `Pay now`,
  thanh_toan_that_bai: `Payment failed`,
  thanh_toan_tien_mat: `Cash`,
  thanh_toan_vietqr: `Pay with VietQR`,
  that_bai: `Fail`,
  thay_doi_mat_khau: `Change your password`,
  thay_doi_mk_thanh_cong: `Change password successfully`,
  thay_doi_ngon_ngu: `Change language `,
  the_noi_dia: `ATM domestic card`,
  the_quoc_te: `VISA, MASTER international card`,
  thich: `Like`,
  thoi_gian: `Time`,
  thoi_gian_ma_xac_minh: `Identified pass valid issue within`,
  thong_bao: `Notice`,
  thong_bao_bql: `Notification from BBM`,
  thong_tin: `Information `,
  thong_tin_ca_nhan: `Personal information`,
  thong_tin_can_ho: `Apartment Information`,
  thong_tin_chuyen_khoan: `Information of transfering`,
  thong_tin_don_gia: `Unit price (include tax and fee)`,
  thu_gon: `Shorten`,
  tien_dien: `Electricity bill`,
  tien_ich: `Utilities`,
  tien_nuoc: `Water bill`,
  tiep_theo: `Next `,
  tiep_tuc: `Continue`,
  tieu_de: `Title `,
  tieu_thu: `Consumption`,
  tieu_thu_nuoc: `Consum of water`,
  tim_kiem: `Search`,
  tin_hay: `News`,
  tinh_nang_phat_trien: `The features are improving`,
  toa: `Building `,
  toi: `To`,
  tong: `Total`,
  tong_can_thanh_toan: `Total of Liability`,
  tong_phat_sinh_thang: `Total monthly arising`,
  tong_phi: `Total `,
  tong_phi_thanh_toan: `Total of Liability`,
  tong_thanh_toan: `Total of Payment`,
  tong_tien: `Total`,
  tra_loi: `Reply`,
  trang_chu: `Home`,
  tro_lai: `Back`,
  tuy_chon: `Option`,
  video: `Video`,
  vo: `Wife`,
  vua_xong: `Just done`,
  vui_long_doi: `Please wait in some minutes`,
  vui_long_doi_cap_nhat: `The data has been downloaded successfully, please wait for update`,
  vui_long_ket_noi: ` No connection, please check wifi, 4G or network connection!`,
  vui_long_thu_lai: `Please try again later`,
  wow: `Wow`,
  xac_minh: `Confirm`,
  xac_nhan_mk_moi: `Confirm your new password`,
  xe_dap: `Bicycle`,
  xe_may: `Motorbike`,
  xem_chi_tiet: `Details`,
  xem_phan_hoi: `See all responses`,
  xem_them: `See more`,
  xem_them_binh_luan: `See more comment`,
  xoa: `Delete`,
  xoa_bai_viet: `Delete post`,
  xoa_y_kien: `Delete comment`,
  xoa_y_kien_thanh_cong: `You have successfully deleted your comment`,
  xong: `Done`,
  y_kien: `Comment`,
  y_kien_danh_gia: `Feedback`,
  yeu_cau_cap_the: `Re-issue the card `,
  yeu_thich: `Like`,
  cap_nhat_thanh_cong: `Updated successfully.`,
  hoi_xoa_binh_luan: `Are you sure you want to delete this comment`,
  sap_dien_ra: `Coming soon`,
  thuong: `Love`,
  tao_bai_viet: `Create post`,
  chinh_sua: `Edit`,
  xoa_thanh_cong: `Delete successfully.`,
  khong_co_qrcode: `No QR code`,
  ma_chuyen_khoan: `Transfer code`,
  phieu_bao_cao: `Report card`,
  phieu_thu_so: `PT No`,
  bang_ke_chi_tiet: `Detailed statistical table`,
  san_pham: `Products`,
  phat_sinh: `Accrued`,
  vui_long_nhap_du: `Please enter all required information`,
  bql_dang_xu_ly: `Processing`,
  cho_phan_hoi_cu_dan: `Waiting for residents to respond`,
  vui_long_nhap_ho_ten: `Please enter your name`,
  anh_xe: `Car photo`,
  xac_nhan: `Confirm`,
  ngay_ket_thuc: `End date`,
  chon_ngay: `Date`,
  quay_video: `Video`,
  chup_anh: `Take a photo`,
  thu_vien: `Library`,
  stt: `No.`,
  phieu_bao_co: `Credit advice`,
  danh_gia_ung_dung: `Review App`,
  mo_ta_danh_gia: `Review app for us to make it better`,
  danh_gia_chuc_nang: `Function evaluation`,
  gop_y_mong_muon: `Your suggestion or your desire`,
  gui_danh_gia: `Submit`,
  danh_sach_phi_xe: `List of vehicle fees`,
  cam_on_danh_gia: `Thank you for evaluate the app, will help us to improve more!`,
  no_chua_thanh_toan: `Unpaid debt`,
  lien_he_bql: `Please contact management for assistance`,
  mien_phi: `Free`,
  cho_bql_xu_ly: `Pending`,
  bql_tiep_nhan: `Reviced to BBM`,
  phan_hoi_bql: `Feedback to BBM`,
  cho_bql_phan_hoi: `Waiting for BBM to respond`,
  hoan_thanh: `Completed`,
  phi: `Fee`,
  chap_nhan_thanh_toan: `Accept payment`,
  so_tien: `Value`,
  binh_chon: `Vote`,
  da_gui_binh_chon: `Vote sent`,
  thanh_toan_thanh_cong: `Payment success`,
  chi_tiet_giao_dich: `Transaction details`,
  dem_binh_chon: `Voted`,
  dich_vu_thang_may: `Register for using the elavator to transfer`,
  dang_ky_thang_may: `Register for using the elavator`,
  dang_ky_su_dung: `Register`,
  danh_sach_phieu_dk: `Listing of register `,
  dang_ky_chuyen_do_vao: `Register to transfering -in`,
  dang_ky_chuyen_do_ra: `Register to transfering - out`,
  nguoi_dang_ky: `Name of register`,
  ngay_van_chuyen: `Date of transfer `,
  hang_hoa_van_chuyen: `Kind of goods `,
  khung_gio: `Time `,
  cam_ket: `Comitment`,
  cam_ket_thang_may: `We commit to abide by these rules `,
  them_hang_hoa: `Add more`,
  tb_dk_thang_may_thanh_cong: `Register successfully for using the elavator`,
  tb_dk_sua_chua_thanh_cong: `Register successfully for reparing `,
  dang_ky_sua_chua: `Register for reparing `,
  nhat_ky_sua_chua: `Diary of reparing `,
  tien_coc_yeu_cau: `Deposit required`,
  da_duyet: `Approve `,
  hoan_thien: `Done `,
  bql_da_nhan_coc: `Deposit required approved by the investor`,
  yeu_cau_bo_sung: `Addtion required`,
  da_coc: `Deposit accepted`,
  dang_thi_cong: `Being working `,
  bql_nhan_ho_so: `The management Board received your file`,
  thoi_gian_bat_dau: `Start`,
  thoi_gian_ket_thuc: `End `,
  noi_dung_de_xuat_sua_chua: `Something need to be repared?  `,
  noi_dung_can_cai_tao: `Something need to be renovated?`,
  nhap_hang_hoa: `Add more the goods please `,
  sai_dinh_dang_sdt: `Your telephone is not right `,
  don_vi_thi_cong: `Unit of building working `,
  thoi_gian_du_kien_thi_cong: `Schedule of construction expected `,
  thong_tin_lien_he: `Contacr form `,
  dien_thoai_lien_he: `Tel`,
  so_luong: `Quantity `,
  so_luong_n: `Quantity `,
  them: `Add `,
  chuyen_do_vao: `Transfering-out `,
  chuyen_do_ra: `Transfering-in `,
  tinh_trang: `Situation `,
  chon_tep: `Choose file `,
  ban_chac_chan_muon_xoa: `Are you sure to delete? `,
  kien_nghi: `Request`,
  ghi_so_dien_nuoc: `Consumption `,
  thay_dong_ho: `Change Power meter`,
  phieu_dang_ky_thang_may: `Elavtor Register Form`,
  phieu_dang_ky_sua_chua: `Fixed Asset Register Form`,
  thong_tin_toa_nha: `Information of building `,
  tu_ngay: `From `,
  den_ngay: `To `,
  phieu_dang_ky_dich_vu: `Services Register Form`,
  yeu_cau: `Require`,
  phuong_tien: `Vehicle`,
  chuyen_trang_thai_phieu: `Changed State of note `,
  bql_da_tiep_nhan: `Received `,
  cho_cdt_phan_hoi: `Waiting for investor's respone`,
  cdt_tu_choi: `The investor refuse`,
  cdt_duyet: `The investor approve `,
  tam_dung: `Pending `,
  sua_thong_tin: `Edit the information `,
  danh_sach_toa_nha: `Listing of building `,
  so_tien_coc_yeu_cau: `Required deposit `,
  vui_long_nhap_so_tien_coc: `Please fill in number of deposit `,
  nhap_so_tien_coc: `Fill in the deposit `,
  chua_xu_ly: `Pending `,
  tim_kiem_theo_can_ho: `Search for the apartments `,
  bo_loc: `Filter `,
  chon_can_ho: `Choose the apartment `,
  phieu: `Note `,
  xin_chao: `Hello`,
  su_kien_sap_dien_ra: `Upcoming Event`,
  lich_bao_tri: `Maintainance Schedule `,
  tin_tuc: `News `,
  khong_co_toa: `You dont have any building, please contact to the management board `,
  ten: `Name `,
  ma_nhan_vien: `Employee code `,
  phan_hoi_cu_dan: `Residents Feedback`,
  phan_hoi_ngay: `Response now`,
  trang_thai: `Status`,
  khong_co_phieu_dk_phuong_tien: `No vehicle register form `,
  khong_co_phieu_dk_thang_may: `No Elavtor Register Form`,
  khong_co_phieu_dk_sua_chua: `Fixed Asset Register Form`,
  khong_co_kien_nghi: `No request `,
  khong_co_bai_viet: `No article`,
  khong_tim_thay_bai_viet: `Dont find your article`,
  khong_tim_thay_phieu: `Dont find your form `,
  dang_ky_phuong_tien: `Register vehicle`,
  bql_da_nhan_ho_so: `We received your document`,
  cdt_duyet_yeu_cau_coc: `The investor approve - require the deposit `,
  them_phuong_tien_he_thong: `Add more vehicle in the system`,
  chi_tiet_kien_nghi: `Detail of your request`,
  ten_phuong_tien: `Name of your vehicle `,
  loai_phuong_tien: `Type of vehicle `,
  ma_the_xe: `Number code of card`,
  ngay_ap_dung_tinh_phi: `Date of beginning charging fees`,
  ngay_ket_thuc_tinh_phi: `Date of finishing charging fees`,
  muc_uu_tien_tinh_phi: `Priority of chargeable`,
  hoat_dong: `Action `,
  them_phuong_tien: `Add more vehicle `,
  quan_ly_cong_viec: `Management `,
  gap: `Urgent `,
  cao: `High `,
  thap: `Short `,
  binh_thuong: `Normal`,
  chua_hoan_thanh: `Not complete`,
  quan_ly_check_list: `Manage of checklist `,
  loc_cong_viec_lap_lai: `Filter repetitive work`,
  nhan_vien_thuc_hien: `Implementation staff`,
  chon_de_loc: `Choose to filter `,
  cho_duyet: `Waiting for approve`,
  cong_viec: `Task`,
  them_cong_viec: `Add more task`,
  ten_cong_viec: `Name of task `,
  loai_cong_viec: `Type of work`,
  muc_do_uu_tien: `Priority `,
  thong_tin_nguoi_nhan_viec: `The information of employee `,
  nguoi_nhan: `Receiver `,
  nguoi_giam_sat: `Supervisor `,
  thong_tin_cong_viec: `Information `,
  chi_tiet_cong_viec: `Details of your task`,
  cai_dat_thoi_gian: `Time setiing `,
  chon_loai_cong_viec: `Choose type of work`,
  them_moi: `Add new `,
  mo_ta_chon_viec: `Selecting Description `,
  mo_ta_cong_viec: `Work description`,
  chon_check_list: `Checklist `,
  nhap_mo_ta_cong_viec: ` Content of Working description `,
  ngay_bat_dau: `Starting date `,
  mo_ta_chon_tg_cv: `Choose the date `,
  cong_viec_lap_lai: `Repetitive work `,
  thu_trong_tuan: `Day of week`,
  theo_tuan: `Filter by week`,
  thoi_gian_hoan_thanh: `Completed time `,
  han_hoan_thanh: `Deadline `,
  thu_hai: `Monday `,
  thu_ba: `Tuesday`,
  thu_tu: `Wednesday`,
  thu_nam: `Thursday`,
  thu_sau: `Friday`,
  thu_bay: `Saturday `,
  chu_nhat: `Sunday`,
  ngay_trong_thang: `Date of month `,
  them_ngay: `Add more day `,
  them_gio: `Add more time `,
  them_phut: `Add more minutes `,
  thang_trong_nam: `Month of year `,
  them_thang: `Add more month`,
  them_nam: `Add more year `,
  sap_xep: `Arrange `,
  bat_buoc_co: `Compulsory `,
  khong_binh_thuong: `Not normal`,
  gia_tri_lua_chon: `Option value`,
  mo_ta_yeu_cau_chi_tiet: `Details of your requirment `,
  them_gia_tri: `Add value `,
  gia_tri_nay_la_loi: `Error value `,
  ten_gia_tri: `Value name`,
  ngay_thuc_hien: `Date `,
  nguoi_thuc_hien: `Excutor `,
  tep_dinh_kem: `Attach file`,
  nguoi_duyet: `Approve by `,
  mo_ta_van_de: `Description of problem `,
  du_doan_van_de: `Guess the problem `,
  cach_giai_quyet: `Solution `,
  chi_tiet_mo_ta: `Details `,
  quan_ly_cong_viec_lap_lai: `Repeated task management`,
  them_check_list: `Add more checklist `,
  dang_mo: `Opening `,
  dang_thuc_hien: `Working`,
  cho_giam_sat_duyet: `Pending approval`,
  loai_check_list: `Types of checklist`,
  them_loai_cong_viec: `Add kind of task`,
  theo_thang: `Filter by month`,
  theo_nam: `Filter by year`,
  theo_quy: `Filter by quarter`,
  thang_mot: `January`,
  thang_hai: `February `,
  thang_ba: `March `,
  ap_dung: `Apply `,
  thang_tu: `April `,
  thang_tam: `August `,
  check_list: `Checklist`,
  check_list_mau: `Checklist templates`,
  xem_theo_khoang_thoi_gian: `Choose by period time`,
  xem_theo_ngay_cu_the: `Choose the particular day`,
  xem_theo_thang_cu_the: `Choose the particular month`,
  thang_muoi_hai: `December `,
  mo_ta_va_check_list: `Description and checklist `,
  da_thuc_hien: `Done `,
  thang_bay: `July `,
  thang_sau: `June `,
  thang_nam: `May`,
  ten_check_list: `Name of checklist `,
  loi_khong_nghiem_trong: `Not serious error `,
  thang_muoi_mot: `November`,
  thang_muoi: `October `,
  luu_mau: `Save `,
  chon_muc_do: `Select  the priority `,
  chon_tat_ca_cac_ngay: `Select all days `,
  chon_tat_ca_cac_thang: `Select all month `,
  chon_thang_lap: `Select repremonth `,
  chon_ngay_trong_tuan: `Select the day in a week`,
  chon_ngay_cuoi_cung_cua_thang: `Select the last day in a month`,
  chon_ngay_lap_trong_thang: `Select the repreday in a month `,
  thang_chin: `September `,
  loi_nghiem_trong: `Serious error`,
  thang_nay: `This month`,
  tuan_nay: `This week `,
  thoi_gian_thuc_hien: `Time `,
  chua_thuc_hien: `Unexecuted work`,
  xem_lich_cong_viec_theo: `View the work schedule by`,
  nhat_ky_cong_viec: `Working diary `,
  cong_viec_lap_lai_theo: ``,
  khong_lap_lai: `Non-repeated`,
  quay_lai_buoc_truoc: `Back `,
  them_tu_check_list_mau: `Add from the form of checklist`,
  chon_tat_ca_ngay: `Select all days`,
  bo_phan: `Department`,
  sao_chep: `Copy `,
  dan: `Paste `,
  ket_qua: `Result `,
  gui_duyet: `Send to `,
  chuyen_trang_thai_cong_viec: `Updte status`,
  yeu_cau_chuyen_ca: `Request of changing the shift`,
  lich_su_cong_viec: `History `,
  chinh_sua_cong_viec: `Edit the work `,
  huy_cong_viec: `Cancel `,
  xoa_cong_viec: `Delete `,
  tao_boi: `Made by `,
  ngay_tao: `Date `,
  chuyen_ca: `Change the shift `,
  lam_lai: `Redo `,
  ket_qua_checklist: `Result of checklist`,
  luu_ket_qua: `Save the result `,
  sua_check_list: `Edit checklist`,
  chon_bo_phan: `Choose department`,
  chon_ca_nhan: `Choose member`,
  tat_ca_bo_phan: `All departments`,
  vui_long_nhap_tieu_de: `Please enter a title`,
  vui_long_chon_loai_cong_viec: `Please select type of work `,
  vui_long_chon_muc_do_uu_tien: `Please select level of priority `,
  vui_long_chon_nguoi_thuc_hien: `Please select the excutor`,
  vui_long_chon_nguoi_giam_sat: `Please select the supervisor`,
  vui_long_nhap_mo_ta: `Please enter the description `,
  vui_long_nhap_ngay_bat_dau: `Please fill the beginning-day`,
  vui_long_nhap_ngay_ket_thuc: `Please fill the ending-day`,
  dat_ten_checklist: `Give a name to checklist form `,
  yeu_cau_duyet: `Request approval`,
  vui_long_chup_anh: `Please take photos`,
  vui_long_quay_video: `Please take videos`,
  chap_nhan_yeu_cau_chuyen_ca: `Approve changing your shift `,
  chap_nhan: `Approved `,
  khong_chap_nhan: `Disapproved`,
  mo_ta_chuyen_ca: `You receive the request chaging shift from `,
  truong_bo_phan: `Head of department `,
  duyet: `Approved `,
  ca_nhan: `Individual `,
  nhan_vien_cung_ban: `Staff `,
  bat: `On `,
  tat: `Off`,
  tham_do_y_kien: `Approaching `,
  hang_ngay: `Daily`,
  lap_lai: `Re-do `,
  ngay_cuoi_cung_thang: `Ending-day of month`,
  tat_ca_ngay: `Allday `,
  tat_ca_cac_thang: `All months `,
  vui_long_nhap_ly_do: `Please enter your reason `,
  danh_sach_yeu_cau_chuyen_ca: `Listing of Chaging-shift requirement `,
  cap_nhat_cong_viec: `Update your work `,
  canh_bao: `Warning message `,
  mo_ta_yc_duyet: `You received the required approvement from `,
  mo_ta_yc_duyet2: `You need to confirm to finish the work `,
  xac_nhan_hoan_thanh: `Confirmed compelete`,
  vui_long_chon_checklist_mau: `Please select checklist form`,
  canh_bao_tg_bat_dau_ket_thuc: `Please choose the starting time is litter than ending time `,
  bat_cong_viec: `On your task `,
  vui_long_cho_trong_giay_lat: `Please waiting in a minute`,
  tai_chinh: `Finance `,
  tien_ich_cong_dong: `Utilities `,
  dang_ky_dich_vu: `Regist the service `,
  loai_tien_ich: `Type of utilities `,
  dang_ky_tien_ich: `Regist the utility `,
  ban_khong_co_quyen: ``,
  da_gui_yeu_cau: `Your require sent `,
  cho_xac_nhan: `Waiting for confirm `,
  da_xac_nhan: `Confirmed `,
  tu_choi: `Refused!`,
  boi: `By`,
  khong_co_phieu: `No note `,
  chuyen_ca_duoc_chap_nhan: `Changing-shift requirement approved `,
  khong_bat_buoc: `No compulsory `,
  thay_doi: `Change `,
  ban_nhan_duoc: `You received `,
  quyen_truy_cap_cong_viec: `Permission enter the work `,
  them_nguoi: `Add person `,
  nhung_nguoi_truy_cap: `Who can be permited to access `,
  them_nguoi_truy_cap: `Add more member `,
  chon_nhan_vien: `Choose the member`,
  quyen_truy_cap: `Access permission `,
  chu_so_huu: `Owner`,
  nguoi_chinh_sua: `Editor`,
  nguoi_xem: `Viewers`,
  xoa_quyen_truy_cap: `Remove access`,
  nhuong_quyen_so_huu: `Transfer of ownership`,
  gop_y: `Feedbacks `,
  mo_ta_danh_gia_ho_tro: `Please give me your feedback that helps Management Board improving our providing services `,
  dang_ky_khach: `Sign up for guest`,
  lich_su_ra_va: `History in-out `,
  thong_tin_phuong_tien: `The information of vehicles `,
  khach_di_kem_phuong_tien: `Vehicel of the guest `,
  phuong_thuc_thanh_toan_phi: `Fee- Payment method `,
  thong_tin_khach: `Infomation of guest `,
  chuong_hinh: `Doorbell camera `,
  camera: `Camera `,
  anh_dai_dien_dich_vu: `Avatar of service`,
  thay_nen: `Change theme `,
  mo_ta_thay_doi_icon: `Click to icon to change `,
  cai_dat_dich_vu: `Setting `,
  tro_lai_de_xuat: `Back to `,
  chon_bieu_tuong: `Choose icon `,
  bo_cuc: `Outline `,
  chia_se: `Share`,
  cai_dat: `Setting `,
  camera_an_ninh: `CCTV `,
  nhan_cuoc_goi: `Receive a call `,
  cuoc_goi_nho: `Missed-call`,
  khong_nhan_cuoc_goi: `No receive a call `,
  lich_su_cuoc_goi: `History of calling `,
  chuong_bao: `Ring alert`,
  goi_loa_ngoai: `Speaker `,
  tu: `From `,
  chu_ho_thanh_toan: `The apartment owner make payment  `,
  khach_thanh_toan: `The guest make a payment `,
  khach: `The guest `,
  da: ``,
  ra: `Out `,
  vao: `In `,
  tai: `At `,
  ma_qr_khong_hop_le: `Qrcode invalid `,
  thoi_gian_ra_vao_het_han: `Notice about your in-out the building out of date `,
  mo: `Open `,
  the_hinh: `Fitness `,
  matxa: `Massage `,
  boi_loi: `Swiming `,
  cb_loai_xe: `Please fill type of vehicle `,
  cb_bien_so_xe: `Please fill payment method `,
  cb_thanh_toan_loai: `Please fill the place `,
  cb_dia_diem: `Please fill the time `,
  cb_thoi_gian: `Please give us your payment photo `,
  cb_thanh_toan_anh: `Please fill period of time `,
  cb_khung_thoi_gian: `Please fill the date to use `,
  cb_ngay_su_dung: `Please fill the ID card `,
  cb_cmnd: `Full Name `,
  cb_ho_ten: `Tel`,
  cb_sdt: `Pass`,
  cb_mat_khau: `Old password `,
  cb_mat_khau_cu: `New password`,
  cb_mat_khau_moi: `Re-fill your new password`,
  cb_mat_khau_moi_lan2: `Register successfully! `,
  tb_thanh_cong_dang_ky: `Delete `,
  tb_thanh_cong_xoa: `Edit `,
  tb_thanh_cong_sua: `Register failure`,
  tb_that_bai_dang_ky: `Delete failure `,
  tb_that_bai_xoa: `Edir failure `,
  tb_that_bai_sua: `Regist Gym `,
  dang_ky_gym: `Regist Gym `,
  dang_ky: ``,
  hinh_thuc_su_dung: `Place `,
  dia_diem: `Select service `,
  chon_goi: `Promotion code `,
  ma_khuyen_mai: `Cost of service `,
  gia_theo_dich_vu: `Special price `,
  uu_dai: ``,
  neu_co: `Note for the service `,
  ghi_chu_cho_dich_vu: `Choose payment method `,
  lua_chon_hinh_thuc_thanh_toan: `Payment Directly `,
  thanh_toan_truc_tiep: `Payment online `,
  thanh_toan_online: `Please choose a service to make payment `,
  hd_thanh_toan_tien_ich: `Debt recorded `,
  ghi_nhan_cong_no: `Attach your payment photo`,
  dinh_kem_hinh_anh_thanh_toan: `Choose type of ticket `,
  chon_loai_ve: ``,
  tong_tam_thoi: ``,
  tong_tam_tinh: `Payment at the desk`,
  thanh_toan_tai_quay: `Register for swimming`,
  dang_ky_boi: `Register for sauna `,
  dang_ky_sauna: `Hot water `,
  nuoc_nong: `Fee for hot water `,
  phi_nuoc_nong: `Search for name of checklist `,
  tim_kiem_check_list: `Update `,
  cap_nhat: `Off `,
  tat_cong_viec: `Please select the department `,
  vui_long_chon_bo_phan: `Change the member`,
  thay_doi_thanh_vien: ``,
  bo_phan_cua_ban: ``,
  ban_chac_chan_muon_huy: ``,
}
