export const VI = {
  giai_doan: "Giai đoạn",
  du_an_noi_bat: "Dự án nổi bật",
  tat_ca_du_an: "Tất cả dự án",
  tin_noi_bo: 'Tin nội bộ',
  tin_du_an: 'Tin dự án',
  lich_mo_ban: 'Lịch mở bán',
  dang_ky_ngay: "Đăng ký ngay",
  thong_tin_gia: "Thông tin giá",
  thong_tin_san_pham: "Thông tin sản phẩm",
  ban_co_chac_chan_duyet: "Bạn có chắc chắn duyệt",
  ma_giao_dich: "Mã giao dịch",
  them_yeu_cau_thanh_toan: "Thêm yêu cầu thanh toán",
  phuong_thuc: "Phương thức",
  thoi_gian_thanh_toan: "Thời gian thanh toán",
  so_tien_ghi_nhan: "Số tiền ghi nhận",
  thoi_gian_duyet: "Thời gian duyệt",
  nhan_vien_yeu_cau: "Nhân viên yêu cầu",
  phong_ban: "Phòng ban",
  giao_dich_thanh_toan: "Giao dịch thanh toán",
  cac_dot_thanh_toan: "Các đợt thanh toán",
  so_tien_thanh_toan_gan_nhat: 'Số tiền thanh toán gần nhất',
  tinh_trang_xy_ly: 'Tình trạng xử lý',
  ly_do_tu_choi: 'Lý do từ chối',
  tong_tien_ke_toan_thuc_thu: 'Tổng tiền kế toán thực thu',
  dien_thoai: 'Điện thoại',
  dia_chi_thuong_tru: 'Địa chỉ thường trú',
  dia_chi_lien_he: 'Địa chỉ liên hệ',
  xem_hop_dong: "Xem hợp đồng",
  ma_hop_dong: 'Mã hợp đồng',
  tong_gia_tri: 'Tổng giá trị',
  tinh_trang_hop_dong: 'Tình trạng hơp đồng',

  thong_tin_hop_dong: "Thông tin hợp đồng",
  chi_tiet_hop_dong: "Chi tiết hợp đồng",
  so_tien_quy_dinh: "Số tiền quy định",
  thong_tin_thanh_toan: 'Thông tin thanh toán',
  loc_hop_dong: "Lọc hợp đồng",
  so_cho_con_lai: "Số chỗ còn lại",
  thong_tin_gio_hang: "Thông tin giỏ hàng",
  loc_gio_hang: "Lọc giổ hàng",
  da_phat: 'Đã phạt',
  da_tha: 'Đã tha',
  ap_dung_tu: "Áp dụng từ",
  ghi_chu_gai_niem_yet: "Ghi chú: Giá niêm yết hiện là giá bán chưa bao gồm VAT và phí bảo trì",
  vui_long_doc_chinh_sach: "(Vui lòng đọc kỹ chính sách bán hàng.Chọn tiêu chí và phương án thanh toán phù hợp)",
  huong_dan_chon_tieu_chi_chinh_sach: 'Chọn tiêu chí Khách hàng thỏa mãn (chọn 1 hoặc nhiều)',
  huong_dan_chon_tieu_chi_thanh_toan: 'Chọn phương án thanh toán* (Chọn 1 phương án)',
  booking: 'Booking',
  hop_dong: 'Hợp đồng',
  mo_ban: 'Mở bán',
  yeu_cau_look: 'Yêu cầu lock',
  chi_tiet_san_pham: 'Chi tiết sản phẩm',
  dien_tich_dat: 'Diện tích tim tường/Diện tích đất',
  dien_tich_san: 'Diện tích thông thủy/Diện tích sàn',
  gia_tim_tuong: 'Giá tim tường',
  gia_thong_thuy: 'Giá thông thủy',
  goc: 'Góc',
  view: 'View',
  huong_cua: 'Hướng cửa',
  huong_ban_cong: 'Hướng ban công',
  so_phong_ngu: 'Số PN: ',
  so_phong_wc: 'Số WC: ',
  TINH_TRANG_SAN_PHAM: 'Giai đoạn sản phẩm',
  chinh_sach_ban_hang: 'Chính sách bán hàng',
  so_bds_thuc_te: 'Số bất động sản thực tế',
  toa_phan_khu: 'Toà phân khu',
  gia_tran: 'Giá trần',
  gia_san: 'Giá sàn',
  gia_niem_yet: 'Giá niêm yết',
  toa_nha_trong: 'Toà nhà trống',
  chon_khach_hang: 'Chọn khách hàng',
  khach_hang_cua_ban: 'Khách hàng của bạn',
  dang_ky_dat_cho: 'Đăng ký đặt chỗ',
  thong_tin_chien_dich: 'Thông tin chiến dịch',
  so_cho_toi_da: 'Số chỗ tối đa',
  so_tien_yeu_cau: 'Số tiền yêu cầu',
  thoi_han: 'Thời hạn',
  dat_cho: 'Đặt chỗ',
  sap_mo: 'Sắp mở',
  dang_mo: 'Đang mở',
  danh_sach_chien_dich: 'Danh sách chiến dịch',
  yeu_cau_hop_dong: 'Yêu cầu hợp đồng',
  thong_tin_du_an: 'Thông tin dự án',
  san_phong_kinh_doanh: 'Sàn/Phòng kinh doanh',
  them_anh_xac_minh: 'Thêm ảnh xác minh',
  bang_hang: 'Bảng hàng',
  loc_du_an: 'Lọc dự án',
  loc_theo_tinh_tp: 'Lọc theo tỉnh thành phố',
  loc_theo_quan_huyen: 'Lọc theo quận huyện',
  loc_theo_loai_hinh: 'Lọc theo loại hình',
  loc_theo_phan_khuc: 'Lọc theo phân khúc',
  thay_doi_anh_dai_dien: 'Thay đổi ảnh',
  thong_bao_khong_giao_dich:
    'Khách hàng chưa có hợp đồng nào phát sinh trên hệ thống',
  loc_theo_du_an: 'Lọc theo dự án',
  giai_trinh_vi_pham: 'Giải trình vi phạm',
  loc_kh_theo_tinh_trang_vi_pham: 'Lọc theo tình trạng vi phạm',
  noi_dung_giai_trinh_chi_tiet: 'Nội dung giải trình chi tiết',
  da_duyet_thanh_cong: 'Đã duyệt thành công',
  chi_tiet_vi_pham: 'Chi tiết vi phạm',
  loc_theo_nhan_vien: 'Lọc theo nhân viên',
  loc_theo_san: 'Lọc theo sàn',
  loc_theo_khach_hang_vi_pham: 'Lọc KH theo vi phạm',
  loc_kh_theo_thoi_gian_tao: 'Lọc KH theo thời gian tạo',
  loc_kh_theo_tinh_trang_cham_soc: 'Lọc KH theo tình trạng chăm sóc',
  loc_kh_theo_nguon: 'Lọc KH theo nguồn',
  loc_kh_theo_loai: 'Lọc KH theo loại',
  loc_kh_theo_nhom_khach_hang: 'Lọc KH theo nhóm ',
  loc_kh_theo_nhom_chien_dich: 'Lọc KH theo nhóm chiến dịch',
  kiem_duyet_giai_trinh: 'Kiểm duyệt giải trình',
  quan_ly_vi_pham: 'Quản lý vi phạm',
  cho_xu_ly: 'Chưa xử lý',
  da_xu_ly: 'Đã xử lý',
  nhap_email_hoac_ten_dang_nhap: 'Nhập email hoặc tên đăng nhập',
  ten_dang_nhap: 'Tên đăng nhập',
  ai_do: 'Ai đó',
  an: 'Ẩn',
  anh_chi_em: 'Anh chị em',
  anh_CMND: 'Ảnh chứng minh nhân dân',
  anh_dang_ky_xe: 'Ảnh đăng ký xe',
  bac: 'Bậc',
  ban_chua_nhap_du: 'Bạn chưa nhập đủ dữ liệu',
  ban_muon_chia_se: 'Bạn muốn chia sẻ gì với cộng đồng',
  bang_chu: 'Bằng chữ',
  bang_ke_dv_thang: 'Bảng kê dịch vụ tháng 6/2022',
  bang_tin: 'Bảng tin',
  bi_danh: 'Bí danh',
  bien_so_xe: 'Biển số xe',
  biet_do_tien_nuoc: 'Biểu đồ tiền nước',
  bieu_do_so_dien: 'Biểu đồ số điện',
  bieu_do_so_nuoc: 'Biểu đồ số nước',
  bieu_do_tien_dien: 'Biểu đồ tiền điện',
  bieu_do_tong_ps_thang: 'Biểu đồ tổng phát sinh hành tháng',
  binh_luan: 'Bình luận',
  bo_me: 'Bố mẹ',
  bo_phan_tiep_nhan: 'Bộ phận tiếp nhận',
  bo_qua: 'Bỏ qua',
  bql: 'Ban quản lý',
  bql_viet_tat: 'BQL',
  buon: 'Buồn',
  cac_dich_vu: 'Các dịch vụ',
  cai_dat_thanh_cong: 'Cài đặt thành công',
  can_cho_phep_sd_cam: 'Bạn cần cho phép ứng dụng sử dụng camera',
  can_ho: 'Căn hộ',
  can_ho_khac: 'Căn khác',
  can_su_dung_bo_nho: 'Bạn cần cho phép ứng dụng sử dụng bộ nhớ.',
  can_thanh_toan: 'Cần thanh toán',
  cap_nhat_sau_khi_tai: 'Ứng dụng sẽ được cập nhật sau khi tải xong',
  cap_nhat_tt_ca_nhan: 'Cập nhật thông tin cá nhân',
  chao: 'Chào',
  chi_nhanh: 'Chi nhánh',
  chi_so_cuoi: 'Chỉ số cuối',
  chi_so_dau: 'Chỉ số đầu',
  chi_tiet: 'Chi tiết',
  chi_tiet_phieu: 'Chi tiết phiếu',
  chi_tiet_y_kien: 'Chi tiết ý kiến',
  cho_phan_hoi: 'Chờ phản hồi',
  cho_phep_may_anh: 'Ban cần cho phép ứng dụng sử dung máy ảnh',
  cho_phep_micro: 'Bạn cần cho phép sử dụng micro',
  chon: 'Chọn',
  chon_anh_bien_so_xe: 'Vui lòng chọn ảnh biển số xe',
  chon_anh_cmnd: 'Vui lòng chọn ảnh CMND/CCCD',
  chon_anh_dk_xe: 'Vui lòng chọn ảnh đăng ký xe',
  chon_bo_phan_tiep_nhan: 'Chọn bộ phận tiếp nhận',
  chon_loai_thanh_toan: 'Quý cư dân vui lòng chọn một dịch vụ để thanh toán!',
  chon_loai_xe: 'Vui lòng chọn loại xe',
  chon_ngay_huy_xe: 'Vui lòng chọn ngày bắt đầu huỷ xe',
  chon_pt_thanh_toan: 'Chọn phương thức thanh toán',
  chon_xe: 'Chọn xe',
  chong: 'Chồng',
  chu_ho: 'Chủ hộ',
  chu_ho_cu: 'Chủ hộ cũ',
  chu_phuong_tien: 'Chủ phương tiện',
  chu_tai_khoan: 'Chủ tài khoản',
  chu_y_chuyen_khoan:
    'Mở ứng dụng ngân hàng, chuyển tới số tài khoản kèm nội dung chuyển khoản bên dưới, để  thực hiện thanh toán',
  chu_y_tai_video: 'Chỉ tải một video và tổng dung lượng nhỏ hơn 50MB',
  chu_y_thanh_toan: 'Số tiền ít nhất có thể thanh toán là 10.000 đồng',
  chu_y_thanh_toan1:
    'Chú ý: Sau khi quét QR Code bạn hãy kiểm tra đúng số tài khoản nhận và Tên chủ tài khoản bên dưới',
  chu_y_thanh_toan2:
    'Nhập đúng nội dung chuyển khoản để thanh toán các dịch vụ bạn đã chọn, nếu nội dung chuyển khoản bạn nhập không đúng hệ thống sẽ tự động thanh toán các dịch vụ ưu tiên',
  chua_su_dung_dich_vu: 'Bạn chưa sử dụng dịch vụ này',
  chua_thanh_toan: 'Chưa thanh toán',
  chua_thanh_toan_du: 'Chưa thanh toán đủ',
  chuyen_khoan_9pay: 'Chuyển khoản ngân hàng 9pay',
  chuyen_khoan_viqr: 'Chuyển khoản qua Viet-QR',
  co: 'Có',
  con_cai: 'Con cái',
  con_lai: 'Còn lại',
  con_no: 'Còn nợ',
  cong_dong: 'Cộng đồng',
  da_cap_nhat: 'Đã cập nhật thành công.',
  da_cap_nhat_y_kien: 'Đã cập nhật ý kiến phản hồi',
  da_gui: 'Đã gửi',
  da_hoan_thanh: 'Đã hoàn thành',
  da_huy: 'Đã huỷ',
  da_ket_thuc: 'Đã kết thúc',
  da_luu_bo_nho: 'Đã lưu vào bộ nhớ đệm',
  da_qua_han: 'Đã quá hạn',
  da_thanh_toan: 'Đã thanh toán',
  da_them_y_kien: 'Đã thêm ý kiến phản hồi',
  da_tiep_nhan: 'Đã tiếp nhận',
  da_xoa_bai_viet: 'Bạn đã xoá bài viết',
  dang_bai: 'Đăng bài',
  dang_cai_dat: 'Đang cài đặt',
  dang_cap_nhat: 'Ứng dụng đang cập nhật dữ liệu',
  dang_cap_nhat2: 'Đang cập nhật',
  dang_dien_ra: 'Đang diễn ra',
  dang_ky_tham_gia: 'Đăng ký tham gia',
  dang_ky_thanh_cong: 'Bạn đã đăng ký thành công',
  dang_ky_xe: 'Đăng ký xe',
  dang_nhap: 'Đăng nhập',
  dang_tai: 'Đang trong quá trình tải',
  dang_xu_ly: 'Đang xử lý',
  dang_xuat: 'Đăng xuất',
  danh_gia: 'Đánh giá',
  danh_gia_bql: 'Đánh giá CLDV Ban quản lý',
  danh_gia_dich_vu: 'Đánh giá dịch vụ',
  danh_muc: 'Danh mục',
  danh_muc_noi_quy: 'Danh mục nội quy',
  danh_muc_tien_ich: 'Danh mục tiện ích',
  danh_sach_phi: 'Danh sách phí',
  danh_sach_thanh_vien: 'Danh sách thành viên',
  danh_sach_xe: 'Danh sách xe',
  danh_sach_yeu_cau: 'Danh sách yêu cầu',
  dat_lai_mat_khau: 'Đặt lại mật khẩu',
  den: 'Đến',
  dia_chi: 'Địa chỉ',
  dia_diem_dong: 'Địa điểm đóng phí',
  dich_vu: 'Dịch vụ',
  dich_vu_dien: 'Dịch vụ điện',
  dich_vu_nuoc: 'Dịch vụ nước',
  dich_vu_phuong_tien: 'Dịch vụ phương tiện',
  dien_ma_code: 'Vui lòng điền mã 6 ký tự đã được gửi đến ',
  dien_tich: 'Diện tích',
  dinh_kem: 'Đính kèm',
  doi_can_ho: 'Đổi căn hộ',
  don_gia: 'Đơn giá',
  don_vi: 'Đơn vị',
  dong: 'Đóng',
  dong_y: 'Đồng ý',
  du_cu: 'Dư cũ',
  dv_tien: 'đồng',
  dv_tien_thu_gon: 'đ',
  email: 'Email',
  email_sdt_sai_dinh_dang: 'Email/số điện thoại không đúng định dạng',
  gan_day_12_thang: '12 tháng gần đây',
  gan_day_3_nam: '3 năm gần đây',
  gan_day_6_thang: '6 tháng gần đây',
  ghi_chu: 'Ghi chú',
  giam_tru: 'Giảm trừ',
  giao_dich_gan_day: 'Giao dịch gần đây',
  giay: 'Giây',
  gio: 'Giờ',
  gioi_tinh: 'Giới tính',
  gioi_tinh_nam: 'Nam',
  gioi_tinh_nu: 'Nữ',
  gui: 'Gửi',
  gui_ngay: 'Gửi ngay',
  gui_phieu_dk_thanh_cong: 'Gửi phiếu đăng ký thành công',
  gui_y_kien: 'Gửi ý kiến',
  gui_yeu_cau_thanh_cong: 'Gửi phiếu yêu cầu thành công',
  haha: 'Haha',
  han: 'Hạn',
  hd_chup_bien_so: 'Ảnh xe(yêu cầu chụp rõ ràng biển số xe)',
  hd_thanh_toan1: 'Mở ứng dụng ngân hàng để thực hiện thanh toán số tiền',
  hd_thanh_toan2: 'kèm nội dung chuyển khoản bên dưới',
  he_thong_nhan_tien: 'Hệ thống đã ghi nhận số tiền của bạn là',
  hinh_anh: 'HÌnh ảnh',
  hinh_thuc: 'Hình thức',
  ho_ten: 'Họ và tên',
  ho_tro: 'Hỗ trợ khẩn cấp',
  hoa_don: 'Hóa đơn',
  hoac: 'Hoặc',
  hoi_dang_xuat: 'Bạn có muốn đăng xuất không',
  hom_nay: 'Hôm nay',
  ht_phan_hoi_lau: 'Hệ thống phản hồi lâu, vui lòng thử lại sau',
  huy: 'Hủy',
  huy_dang_ky: 'Hủy đăng ký',
  huy_dang_ky_thanh_cong: 'Bạn đã huỷ đăng ký thành công',
  huy_dich_vu: 'Huỷ dịch vụ',
  huy_tham_gia: 'HUỶ THAM GIA',
  khac: 'Khác',
  khach_thue: 'Khách thuê',
  khong: 'Không',
  khong_co_bang_tin: 'Không có bảng tin nào',
  khong_co_du_lieu: 'Không có dữ liệu',
  khong_co_hoa_don: 'Không có hóa đơn',
  khong_co_nha:
    'Tài khoản của bạn không sở hữu căn hộ nào, nếu không đúng vui lòng liên hệ BQL để được hỗ trợ!',
  khong_co_noi_dung: 'Không có nội dung',
  khong_co_phieu_thu: 'Không có phiếu thu nào',
  khong_co_su_kien: 'Không có sự kiện',
  khong_co_thong_bao: 'Không có thông báo',
  khong_co_tin_moi: 'Không có tin mới nào',
  khong_co_y_kien_dg: 'Không có ý kiến, đánh giá nào',
  khong_dang_ky_duoc: 'Không thể đăng ký được',
  khong_hien_thi: 'Không hiển thị',
  khong_huy_dang_ky_duoc: 'Không thể huỷ đăng ký được',
  khong_mo_file_duoc: 'Không thể mở file',
  khong_su_dung_dv: 'Không sử dụng dịch vụ trong thời gian qua',
  khong_tai_file_duoc: 'Không tải file xuống được',
  khong_thanh_cong: 'Không thành công',
  ky_tu: 'ký tự',
  lich_su_giao_dich: 'Lịch sử giao dịch',
  lich_su_thanh_toan: 'Lịch sử thanh toán',
  lien_ket: 'liên kết',
  loai_xe: 'Loại xe',
  loi_ket_noi: 'Lỗi kết nối',
  luc: 'Lúc',
  luu: 'Lưu',
  luu_lai: 'Lưu lại',
  ly_do: 'Lý do',
  ma_can_ho: 'Mã căn hộ',
  ma_code_6_kt: 'Mã code phải là 6 ký tự',
  ma_code_chua_nhap: 'Mã code chưa được nhập',
  ma_loi: 'mã lỗi',
  mat_khau: 'Mật khẩu',
  mat_khau_khong_khop: 'Mật khẩu không khớp',
  mat_khau_sai_dinh_dang: 'Mật khẩu không đúng định dạng, tối thiểu 6 ký tự',
  may_chu_loi: 'Máy chủ đang lỗi, vui lòng thử lại sau',
  mo_ta: 'Mô tả',
  mo_ta_can_ho: 'Mô tả căn hộ',
  mo_ta_y_kien_danh_gia:
    'Ý kiến, đánh giá của bạn giúp chúng tôi cải thiện dịch vụ',
  nam_nay: 'Năm nay',
  nang_cap_ung_dung: 'Nâng cấp ứng dụng',
  ngan_hang: 'Ngân hàng',
  ngay: 'Ngày',
  ngay_bat_dau_sd: 'Ngày bắt đầu sử dụng dự kiến',
  ngay_cap: 'Ngày cấp',
  ngay_du_kien_huy: 'Ngày dự kiến huỷ',
  ngay_ket_thuc_sd: 'Ngày kết thúc sử dụng dự kiến',
  ngay_sinh: 'Ngày sinh',
  ngay_tham_gia: 'Ngày tham gia',
  ngay_thanh_toan: 'Ngày thanh toán',
  ngon_ngu: 'Ngôn ngữ',
  nguoi_nop: 'Người nộp',
  nguoi_trong_can_ho: 'Người trong căn hộ',
  nhan_otp: 'Nhận mã OTP',
  nhap_bien_so_xe: 'Vui lòng nhập biển số xe',
  nhap_ly_do: 'Nhập lý do',
  nhap_ma_tai_day: 'Nhập mã tại đây',
  nhap_mail_sdt: 'Nhập SĐT hoặc email đăng nhập',
  nhap_mat_khau: 'Nhập mật khẩu',
  nhap_mk_hien_tai: 'Nhập mật khẩu hiện tại',
  nhap_mk_moi: 'Nhập mât khẩu mới',
  nhap_ngay: 'Nhập ngày',
  nhap_ngay_bat_dau: 'Vui lòng nhập ngày bắt đầu sử dụng',
  nhap_noi_dung: 'Nhập nội dung',
  nhap_tai_day: 'Nhập tại đây',
  nhap_tieu_de_noi_dung: 'Bạn cần nhập đầy đủ tiêu đề/nội dung',
  no_cu: 'Nợ cũ',
  noi_cap: 'Nơi cấp',
  noi_dung: 'Nội dung',
  noi_dung_chuyen_khoan: 'Nội dung chuyển khoản',
  noi_dung_thanh_toan: 'Nội dung thanh toán',
  noi_quy: 'Nội Quy',
  o_to: 'Ô tô',
  phan_no: 'Phẫn nộ',
  phat_sinh_thang: 'Phát sinh hàng tháng',
  phat_sinh_trong_ky: 'Phát sinh trong kỳ',
  phi_dich_vu: 'Phí dịch vụ',
  phi_dien: 'Phí điện',
  phi_khac: 'Phí khác',
  phi_nuoc: 'Phí nước',
  phi_phuong_tien: 'Phí phương tiện',
  phi_thang: 'Phí dịch vụ tháng',
  phien_ban_moi_nhat: 'Phiên bản hiện tại là mới nhất',
  phieu_thu: 'Phiếu thu',
  phieu_yeu_cau: 'Phiếu yêu cầu',
  phut: 'Phút',
  qua_han_va_con_no: 'Quá hạn và còn nợ',
  quan_he_chu_ho: 'Quan hệ với chủ hộ',
  quay_lai: 'Quay lại',
  quen: 'Quên',
  quen_mat_khau: 'Quên mật khẩu',
  quet_qr: 'Quét mã QRCode',
  quet_qr_chuyen_khoan: 'Quét QR để chuyển khoản',
  quet_qr_danh_gia: 'Quét QR-code để đánh giá dịch vụ',
  sai_dinh_dang: 'Sai định dạng',
  sdt: 'Số điện thoại',
  sdt_khan_cap: 'Hotline',
  se_tham_gia: 'Sẽ tham gia',
  so: 'số',
  so_bang_ke: 'Số bảng kê',
  so_CMND: 'Số CMND',
  so_du: 'Số dư',
  so_du_can_ho: 'Số dư căn hộ',
  so_tai_khoan: 'Số tài khoản',
  so_tien_bang_chu: 'Số tiền bằng chữ',
  so_tien_nop: 'Số tiền nộp',
  so_tk_nhan: 'Số tài khoản nhận',
  su_kien: 'Sự kiện',
  su_kien_ket_thuc: 'Sự kiện đã kết thúc',
  sua: 'Sửa',
  sua_bai_viet: 'Sửa bài viết',
  sua_y_kien: 'Sửa ý kiến',
  tai_day: 'tại đây',
  tai_khoan_nhan_thanh_toan: 'Tài khoản nhận thanh toán',
  tai_xuong: 'Tải xuống',
  tang: 'Tầng',
  tat_ca: 'Tất cả',
  tat_ca_anh_video: 'Tất cả ảnh/video',
  tat_ca_hoa_don: 'Tất cả hóa đơn',
  tat_ca_no: 'Tất cả nợ',
  ten_can_ho: 'Tên căn hộ',
  ten_chu_ho: 'Tên chủ hộ',
  ten_chu_khoan: 'Tên chủ khoản',
  ten_dich_vu: 'Tên dịch vụ',
  ten_ngan_hang: 'Tên ngân hàng',
  thac_mac_lien_he:
    'Nếu bạn có thắc mắc, xin phản hồi về BQL thông qua các hình thức:',
  thang: 'Tháng',
  thanh_cong: 'Thành công',
  thanh_tien: 'Thành tiền',
  thanh_toan: 'Thanh toán',
  thanh_toan_chua_du: 'Thanh toán chưa đủ',
  thanh_toan_chuyen_khoan: 'Thanh toán chuyển khoản',
  thanh_toan_ngay: 'Thanh toán ngay',
  thanh_toan_that_bai: 'Thanh toán thất bại',
  thanh_toan_tien_mat: 'Thanh toán tiền mặt',
  thanh_toan_vietqr: 'Thanh toán qua VietQr',
  that_bai: 'Thất bại',
  thay_doi_mat_khau: 'Thay đổi mật khẩu',
  thay_doi_mk_thanh_cong: 'Thay đổi mật khẩu thành công',
  thay_doi_ngon_ngu: 'Thay đổi ngôn ngữ',
  the_noi_dia: 'Thẻ nội địa ATM',
  the_quoc_te: 'Thẻ quốc tế VISA, MASTER',
  thich: 'Thích',
  thoi_gian: 'Thời gian',
  thoi_gian_ma_xac_minh: 'Mã xác minh có hiệu lực trong',
  thong_bao: 'Thông báo',
  thong_bao_bql: 'Thông báo từ BQL',
  thong_tin: 'Thông tin',
  thong_tin_ca_nhan: 'Thông tin cá nhân',
  thong_tin_can_ho: 'Thông tin căn hộ',
  thong_tin_chuyen_khoan: 'Thông tin chuyển khoản',
  thong_tin_don_gia: 'Đơn giá đã bao gồm thuế và phí theo quy định',
  thu_gon: 'Thu gọn',
  tien_dien: 'Tiền điện',
  tien_ich: 'Tiện ích',
  tien_nuoc: 'Tiền nước',
  tiep_theo: 'Tiếp theo',
  tiep_tuc: 'Tiếp tục',
  tieu_de: 'Tiêu đề',
  tieu_thu: 'Tiêu thụ',
  tieu_thu_nuoc: 'Tiêu thụ nước',
  tim_kiem: 'Tìm kiếm',
  tin_hay: 'Tin hay',
  tinh_nang_phat_trien: 'Tính năng đang phát triển!',
  toa: 'Tòa',
  toi: 'Tới',
  tong: 'Tổng',
  tong_can_thanh_toan: 'Tổng cần thanh toán',
  tong_phat_sinh_thang: 'Tổng phát sinh hàng tháng',
  tong_phi: 'Tổng phí ',
  tong_phi_thanh_toan: 'Tổng phí cần thanh toán',
  tong_thanh_toan: 'Tổng thanh toán',
  tong_tien: 'Tổng tiền',
  tra_loi: 'Trả lời',
  trang_chu: 'Trang chủ',
  tro_lai: 'Trở lại',
  tuy_chon: 'Tuỳ chọn',
  video: 'Video',
  vo: 'Vợ',
  vua_xong: 'Vừa xong',
  vui_long_doi: 'Vui lòng đợi trong giây lát',
  vui_long_doi_cap_nhat:
    'Dữ liệu đã tải xuống thành công, vui lòng đợi cập nhật',
  vui_long_ket_noi:
    'Mất kết nối, vui lòng kiểm tra lại wifi, 4G hoặc đường truyền mạng !',
  vui_long_thu_lai: 'Vui lòng thử lại sau',
  wow: 'Wow',
  xac_minh: 'Xác minh',
  xac_nhan_mk_moi: 'Xác nhận mật khẩu mới',
  xe_dap: 'Xe đạp',
  xe_may: 'Xe máy',
  xem_chi_tiet: 'Xem chi tiết',
  xem_phan_hoi: 'Xem phản hồi',
  xem_them: 'Xem thêm',
  xem_them_binh_luan: 'Xem thêm bình luận',
  xoa: 'Xoá',
  xoa_bai_viet: 'Xoá bài viết',
  xoa_y_kien: 'Xoá ý kiến',
  xoa_y_kien_thanh_cong: 'Bạn đã xoá ý kiến thành công',
  xong: 'Xong',
  y_kien: 'Ý kiến',
  y_kien_danh_gia: 'Ý kiến đánh giá',
  yeu_cau_cap_the: 'Yêu cầu cấp lại thẻ',
  yeu_thich: 'Yêu thích',
  cap_nhat_thanh_cong: 'Đã cập nhật thành công',
  hoi_xoa_binh_luan: 'Bạn có chắc chắn muốn xoá bình luận này không',
  sap_dien_ra: 'Sắp diễn ra',
  thuong: 'Thương',
  tao_bai_viet: 'Tạo bài viết',
  chinh_sua: 'Chỉnh sửa',
  xoa_thanh_cong: 'Xoá thành công',
  khong_co_qrcode: 'Không có mã Qr Code',
  ma_chuyen_khoan: 'Mã chuyển khoản',
  phieu_bao_cao: 'Phiếu báo cáo',
  phieu_thu_so: 'PT số',
  bang_ke_chi_tiet: 'Bảng kê chi tiết',
  san_pham: 'Sản phầm',
  phat_sinh: 'Phát sinh',
  vui_long_nhap_du: 'Vui lòng nhập đủ thông tin theo yêu cầu',
  bql_dang_xu_ly: 'BQL đang xử lý',
  cho_phan_hoi_cu_dan: 'Chờ cư dân phản hồi',
  vui_long_nhap_ho_ten: 'Vui lòng nhập họ tên',
  anh_xe: 'Ảnh xe',
  xac_nhan: 'Xác nhận',
  ngay_ket_thuc: 'Ngày kết thúc',
  chon_ngay: 'Chọn ngày',
  quay_video: 'Quay video',
  chup_anh: 'Chụp ảnh',
  thu_vien: 'Thư viện',
  stt: 'STT',
  phieu_bao_co: 'Phiếu báo có',
  danh_gia_ung_dung: 'Đánh giá ứng dụng',
  mo_ta_danh_gia: 'Đánh giá ứng dụng để chúng tôi cải thiện tốt hơn',
  danh_gia_chuc_nang: 'Đánh giá chức năng',
  gop_y_mong_muon: 'Góp ý hoặc mong muốn',
  gui_danh_gia: 'Gửi đánh giá',
  danh_sach_phi_xe: 'Danh sách phí xe',
  cam_on_danh_gia:
    'Cảm ơn bạn đã đánh giá ứng dụng, sẽ giúp chúng tôi cải thiện nhiều hơn !',
  no_chua_thanh_toan: 'Nợ chưa thanh toán',
  lien_he_bql: 'Vui lòng liên hệ ban quản lý để được hỗ trợ',
  mien_phi: 'Miễn phí',
  cho_bql_xu_ly: 'Chờ BQL xử lý',
  bql_tiep_nhan: 'BQL đã tiếp nhận',
  phan_hoi_bql: 'Phản hồi BQL',
  cho_bql_phan_hoi: 'Chờ BQL phản hồi',
  hoan_thanh: 'Hoàn thành',
  phi: 'Phí',
  chap_nhan_thanh_toan: 'Chấp nhận thanh toán',
  so_tien: 'Số tiền',
  binh_chon: 'Bình chọn',
  da_gui_binh_chon: 'Đã gửi bình chọn',
  thanh_toan_thanh_cong: 'Thanh toán thành công',
  chi_tiet_giao_dich: 'Chi tiết giao dịch',
  dem_binh_chon: 'Người đã tham gia bình chọn',
  dich_vu_thang_may: 'Đăng ký sử dụng thang máy chuyển đồ ra/vào',
  dang_ky_thang_may: 'Đăng ký sử dụng thang máy',
  dang_ky_su_dung: 'Đăng ký sử dụng',
  danh_sach_phieu_dk: 'Danh sách phiếu đăng ký',
  dang_ky_chuyen_do_vao: 'Đăng ký chuyển đồ vào',
  dang_ky_chuyen_do_ra: 'Đăng ký chuyển đồ ra',
  nguoi_dang_ky: 'Người đăng ký',
  ngay_van_chuyen: 'Ngày vận chuyển',
  hang_hoa_van_chuyen: 'Hàng hoá vận chuyển',
  khung_gio: 'Khung giờ',
  cam_ket: 'Cam kết',
  cam_ket_thang_may: 'Chúng tôi cam kết tuân thủ các quy định sau',
  them_hang_hoa: 'Thêm hàng hoá',
  tb_dk_thang_may_thanh_cong: 'Đăng ký thành công sử dụng thang máy',
  tb_dk_sua_chua_thanh_cong: 'Đăng ký thành công sửa chữa',
  dang_ky_sua_chua: 'Đăng ký sửa chữa',
  nhat_ky_sua_chua: 'Nhật ký sửa chữa',
  tien_coc_yeu_cau: 'Tiền cọc yêu cầu',
  da_duyet: 'Đã duyệt',
  hoan_thien: 'Hoàn thiện',
  bql_da_nhan_coc: 'CĐT đã duyệt yêu cầu cọc',
  yeu_cau_bo_sung: 'Yêu cầu bổ sung',
  da_coc: 'Đã cọc',
  dang_thi_cong: 'Đang thi công',
  bql_nhan_ho_so: 'BQL đã nhận hồ sơ',
  thoi_gian_bat_dau: 'Thời gian bắt đầu',
  thoi_gian_ket_thuc: 'Thời gian kết thúc',
  noi_dung_de_xuat_sua_chua: 'Nội dung đề xuất sửa chữa',
  noi_dung_can_cai_tao: 'Nội dung cần cải tạo',
  nhap_hang_hoa: 'Vui lòng thêm hàng hoá',
  sai_dinh_dang_sdt: 'Số điện thoại sai định dạng!',
  don_vi_thi_cong: 'Đơn vị thi công',
  thoi_gian_du_kien_thi_cong: 'Thời gian dự kiến thi công',
  thong_tin_lien_he: 'Thông tin liên hệ',
  dien_thoai_lien_he: 'Điện thoại liên hệ',
  so_luong: 'Số lượng',
  so_luong_n: 'SL',
  them: 'Thêm',
  chuyen_do_vao: 'Chuyển đồ vào',
  chuyen_do_ra: 'Chuyển đồ ra',
  tinh_trang: 'Tình trạng',
  chon_tep: 'Chọn tệp',
  ban_chac_chan_muon_xoa: 'Bạn chắc chắn muốn xoá?',
  kien_nghi: 'Kiến nghị',
  ghi_so_dien_nuoc: 'Ghi số điện nước',
  thay_dong_ho: 'Thay đồng hồ',
  phieu_dang_ky_thang_may: 'Phiếu đăng ký thang máy',
  phieu_dang_ky_sua_chua: 'Phiếu đăng ký sửa chữa',
  thong_tin_toa_nha: 'Thông tin toà nhà',
  tu_ngay: 'Từ ngày',
  den_ngay: 'Đến ngày',
  phieu_dang_ky_dich_vu: 'Phiếu đăng ký dịch vụ',
  yeu_cau: 'Yêu cầu',
  phuong_tien: 'Phương tiện',
  chuyen_trang_thai_phieu: 'Chuyển trạng thái phiếu',
  bql_da_tiep_nhan: 'BQL đã tiếp nhận',
  cho_cdt_phan_hoi: 'Chờ CĐT phản hồi',
  cdt_tu_choi: 'CĐT từ chối',
  cdt_duyet: 'CĐT duyệt',
  tam_dung: 'Tạm dừng',
  sua_thong_tin: 'Sửa thông tin',
  danh_sach_toa_nha: 'Danh sách toà nhà',
  so_tien_coc_yeu_cau: 'Số tiền cọc yêu cầu',
  vui_long_nhap_so_tien_coc: 'Vui lòng nhập số tiền cọc',
  nhap_so_tien_coc: 'Nhập số tiền cọc',
  chua_xu_ly: 'Chưa xử lý',
  tim_kiem_theo_can_ho: 'Tìm kiếm theo căn hộ',
  bo_loc: 'Bộ lọc',
  chon_can_ho: 'Chọn căn hộ',
  phieu: 'Phiếu',
  xin_chao: 'Xin chào',
  su_kien_sap_dien_ra: 'Sự kiện sắp diễn ra',
  lich_bao_tri: 'Lịch bảo trì',
  tin_tuc: 'Tin tức',
  khong_co_toa:
    'Bạn đang không có toà nào cả, vui lòng liên hệ ban quản lý kiểm tra',
  ten: 'Tên',
  ma_nhan_vien: 'Mã nhân viên',
  phan_hoi_cu_dan: 'Phản hồi cư dân',
  phan_hoi_ngay: 'Phản hồi ngay',
  trang_thai: 'Trạng thái',
  khong_co_phieu_dk_phuong_tien: 'Không có phiếu đăng ký phương tiện',
  khong_co_phieu_dk_thang_may: 'Không có phiếu đăng ký thang máy',
  khong_co_phieu_dk_sua_chua: 'Không có phiếu đăng ký sửa chữa',
  khong_co_kien_nghi: 'Không có kiến nghị',
  khong_co_bai_viet: 'Không có bài viết',
  khong_tim_thay_bai_viet: 'Không tìm thấy bài viết',
  khong_tim_thay_phieu: 'Không tìm thấy phiếu',
  dang_ky_phuong_tien: 'Đăng ký phương tiện',
  bql_da_nhan_ho_so: 'BQL đã nhận hồ sơ',
  cdt_duyet_yeu_cau_coc: 'CĐT duyệt - yêu cầu cọc',
  them_phuong_tien_he_thong: 'Thêm phương tiện vào hệ thống',
  chi_tiet_kien_nghi: 'Chi tiết kiến nghị',
  ten_phuong_tien: 'Tên phương tiện',
  loai_phuong_tien: 'Loại phương tiện',
  ma_the_xe: 'Mã thẻ xe',
  ngay_ap_dung_tinh_phi: 'Ngày áp dụng tính phí',
  ngay_ket_thuc_tinh_phi: 'Ngày kết thúc tính phí',
  muc_uu_tien_tinh_phi: 'Mức ưu tiên tính phí',
  hoat_dong: 'Hoạt động',
  them_phuong_tien: 'Thêm phương tiện',
  quan_ly_cong_viec: 'Quản lý công việc',
  gap: 'Gấp',
  cao: 'Cao',
  thap: 'Thấp',
  binh_thuong: 'Bình thường',
  chua_hoan_thanh: 'Chưa hoàn thành',
  quan_ly_check_list: 'Quản lý checklist',
  loc_cong_viec_lap_lai: 'Lọc công việc lặp lại',
  nhan_vien_thuc_hien: 'Nhân viên thực hiện',
  chon_de_loc: 'Chọn để lọc',
  cho_duyet: 'Chờ duyệt',
  cong_viec: 'Công việc',
  them_cong_viec: 'Thêm công việc',
  ten_cong_viec: 'Tên công việc',
  loai_cong_viec: 'Loại công việc',
  muc_do_uu_tien: 'Mức độ ưu tiên',
  thong_tin_nguoi_nhan_viec: 'Thông tin người nhận việc',
  nguoi_nhan: 'Người nhận',
  nguoi_giam_sat: 'Người giám sát',
  thong_tin_cong_viec: 'Thông tin công việc',
  chi_tiet_cong_viec: 'Chi tiết công việc',
  cai_dat_thoi_gian: 'Cài đặt thời gian',
  chon_loai_cong_viec: 'Chọn loại công việc',
  them_moi: 'Thêm mới',
  mo_ta_chon_viec: 'Mô tả chọn việc',
  mo_ta_cong_viec: 'Mô tả công việc',
  chon_check_list: 'Chọn checklist',
  nhap_mo_ta_cong_viec: 'Nhập mô tả công việc',
  ngay_bat_dau: 'Ngày bắt đầu',
  mo_ta_chon_tg_cv: 'Mô tả chọn thời gian công việc',
  cong_viec_lap_lai: 'Công việc lặp lại',
  thu_trong_tuan: 'Thứ trong tuần',
  theo_tuan: 'Theo tuần',
  thoi_gian_hoan_thanh: 'Thời gian hoàn thành',
  han_hoan_thanh: 'Hạn hoàn thành',
  thu_hai: 'Thứ Hai',
  thu_ba: 'Thứ ba',
  thu_tu: 'Thứ tư',
  thu_nam: 'Thứ năm',
  thu_sau: 'Thứ sáu',
  thu_bay: 'Thứ bảy',
  chu_nhat: 'Chủ nhật',
  ngay_trong_thang: 'Ngày trong tháng',
  them_ngay: 'Thêm ngày',
  them_gio: 'Thêm giờ',
  them_phut: 'Thêm phút',
  thang_trong_nam: 'Tháng trong năm',
  them_thang: 'Thêm tháng',
  them_nam: 'Thêm năm',
  sap_xep: 'Sắp xếp',
  bat_buoc_co: 'Bắt buộc có',
  khong_binh_thuong: 'Không bình thường',
  gia_tri_lua_chon: 'Giá trị lựa chọn',
  mo_ta_yeu_cau_chi_tiet: 'Mô tả yêu cầu chi tiết',
  them_gia_tri: 'Thêm giá trị',
  gia_tri_nay_la_loi: 'Giá trị này là lỗi',
  ten_gia_tri: 'Tên giá trị',
  ngay_thuc_hien: 'Ngày thực hiện',
  nguoi_thuc_hien: 'Người thực hiện',
  tep_dinh_kem: 'Tệp đính kèm',
  nguoi_duyet: 'Người duyệt',
  mo_ta_van_de: 'Mô tả vấn đề',
  du_doan_van_de: 'Dự đoán vấn đề',
  cach_giai_quyet: 'Cách giải quyết',
  chi_tiet_mo_ta: 'Chi tiết mô tả',
  quan_ly_cong_viec_lap_lai: 'Quản lý công việc lặp lại',
  them_check_list: 'Thêm checklist',
  dang_thuc_hien: 'Đang thực hiện',
  cho_giam_sat_duyet: 'Chờ giám sát duyệt',
  loai_check_list: 'Loại checklist',
  them_loai_cong_viec: 'Thêm loại công việc',
  theo_thang: 'Theo tháng',
  theo_nam: 'Theo năm',
  theo_quy: 'Theo quý',
  thang_mot: 'Tháng một',
  thang_hai: 'Tháng hai',
  thang_ba: 'Tháng ba',
  ap_dung: 'Áp dụng',
  thang_tu: 'Tháng tư',
  thang_tam: 'Tháng tám',
  check_list: 'CheckList',
  check_list_mau: 'Checklist mẫu',
  xem_theo_khoang_thoi_gian: 'Xem theo khoảng thời gian',
  xem_theo_ngay_cu_the: 'Xem theo ngày cụ thể',
  xem_theo_thang_cu_the: 'Xem theo tháng cụ thể',
  thang_muoi_hai: 'Tháng mười hai',
  mo_ta_va_check_list: 'Mô tả và checklist',
  da_thuc_hien: 'Đã thực hiện',
  thang_bay: 'Tháng bảy',
  thang_sau: 'Tháng sáu',
  thang_nam: 'Tháng năm',
  ten_check_list: 'Tên checklist',
  loi_khong_nghiem_trong: 'Lỗi không nghiêm trọng',
  thang_muoi_mot: 'Tháng mười một',
  thang_muoi: 'Tháng mười',
  luu_mau: 'Lưu mẫu',
  chon_muc_do: 'Chọn mức độ',
  chon_tat_ca_cac_ngay: 'Chọn tất cả các ngày',
  chon_tat_ca_cac_thang: 'Chọn tất cả các tháng',
  chon_thang_lap: 'Chọn tháng lặp',
  chon_ngay_trong_tuan: 'Chọn ngày trong tuần',
  chon_ngay_cuoi_cung_cua_thang: 'Chọn ngày cuối cùng của tháng',
  chon_ngay_lap_trong_thang: 'Chọn ngày lặp trong tháng',
  thang_chin: 'Tháng chín',
  loi_nghiem_trong: 'Lỗi nghiêm trọng',
  thang_nay: 'Tháng này',
  tuan_nay: 'Tuần này',
  thoi_gian_thuc_hien: 'Thời gian thực hiện',
  chua_thuc_hien: 'Chưa thực hiện',
  xem_lich_cong_viec_theo: 'Xem lịch công việc theo',
  nhat_ky_cong_viec: 'Nhật ký công việc',
  cong_viec_lap_lai_theo: 'Công việc lặp lại theo',
  khong_lap_lai: 'Không lặp lại',
  quay_lai_buoc_truoc: 'Quay lại bước trước',
  them_tu_check_list_mau: 'Thêm từ checklist mẫu',
  chon_tat_ca_ngay: 'Chọn tất cả ngày',
  bo_phan: 'Bộ phận',
  sao_chep: 'Sao chép',
  dan: 'Dán',
  ket_qua: 'Kết quả',
  gui_duyet: 'Gửi duyệt',
  chuyen_trang_thai_cong_viec: 'Chuyển trạng thái công việc',
  yeu_cau_chuyen_ca: 'Y/c chuyển ca',
  lich_su_cong_viec: 'Lịch sử công việc',
  chinh_sua_cong_viec: 'Chỉnh sửa công việc',
  huy_cong_viec: 'Huỷ công việc',
  xoa_cong_viec: 'Xoá công việc',
  tao_boi: 'Tạo bởi',
  ngay_tao: 'Ngày tạo',
  chuyen_ca: 'Chuyển ca',
  lam_lai: 'Làm lại',
  ket_qua_checklist: 'Kết quả checklist',
  luu_ket_qua: 'Lưu kết quả',
  sua_check_list: 'Sửa checklist',
  chon_bo_phan: 'Chọn bộ phận',
  chon_ca_nhan: 'Chọn cá nhân',
  tat_ca_bo_phan: 'Tất cả bộ phận',
  vui_long_nhap_tieu_de: 'Vui lòng nhập tiêu đề',
  vui_long_chon_loai_cong_viec: 'Vui lòng chọn loại công việc',
  vui_long_chon_muc_do_uu_tien: 'Vui lòng chọn mức độ ưu tiên',
  vui_long_chon_nguoi_thuc_hien: 'Vui lòng chọn người thực hiện',
  vui_long_chon_nguoi_giam_sat: 'Vui lòng chọn người giám sát',
  vui_long_nhap_mo_ta: 'Vui lòng nhập mô tả',
  vui_long_nhap_ngay_bat_dau: 'Vui lòng nhập ngày bắt đầu',
  vui_long_nhap_ngay_ket_thuc: 'Vui lòng nhập ngày kết thúc',
  dat_ten_checklist: 'Đặt tên cho file checklist mẫu',
  yeu_cau_duyet: 'Y/c duyệt',
  vui_long_chup_anh: 'Bạn vui lòng chụp ảnh',
  vui_long_quay_video: 'Bạn vui lòng quay video',
  chap_nhan_yeu_cau_chuyen_ca: 'Chấp nhận yêu cầu chuyển ca',
  chap_nhan: 'Chấp nhận',
  khong_chap_nhan: 'Không chấp nhận',
  mo_ta_chuyen_ca: 'Bạn nhận được yêu cầu chuyển ca từ',
  truong_bo_phan: 'Trưởng bộ phận',
  duyet: 'Duyệt',
  ca_nhan: 'Cá nhân',
  nhan_vien_cung_ban: 'Nhân viên cùng ban',
  bat: 'Bật',
  tat: 'Tắt',
  tham_do_y_kien: 'Thăm dò ý kiến',
  hang_ngay: 'Hằng ngày',
  lap_lai: 'Lặp lại',
  ngay_cuoi_cung_thang: 'Ngày cuối cùng của tháng',
  tat_ca_ngay: 'Tất cả ngày',
  tat_ca_cac_thang: 'Tất cả các tháng',
  vui_long_nhap_ly_do: 'Vui lòng nhập lý do',
  danh_sach_yeu_cau_chuyen_ca: 'Danh sách yêu cầu chuyển ca',
  cap_nhat_cong_viec: 'Cập nhật công việc',
  canh_bao: 'Cảnh báo',
  mo_ta_yc_duyet: 'Bạn nhận được yêu cầu duyệt từ',
  mo_ta_yc_duyet2: 'Bạn cần xác nhận để giúp công việc được hoàn thành',
  xac_nhan_hoan_thanh: 'Xác nhận hoàn thành',
  vui_long_chon_checklist_mau: 'Vui lòng chọn checklist mẫu',
  canh_bao_tg_bat_dau_ket_thuc:
    'Vui lòng chọn thời gian bắt đầu nhỏ hơn thời gian kết thúc',
  bat_cong_viec: 'Bật công việc',
  vui_long_cho_trong_giay_lat: 'Vui lòng chờ trong giây lát',
  tai_chinh: 'Tài chính',
  tien_ich_cong_dong: 'Tiện ích cộng đồng',
  dang_ky_dich_vu: 'Đăng ký dịch vụ',
  loai_tien_ich: 'Loại tiện ích',
  dang_ky_tien_ich: 'Đăng ký tiện ích',
  ban_khong_co_quyen: 'Bạn không có quyền',
  da_gui_yeu_cau: 'Đã gửi yêu cầu',
  cho_xac_nhan: 'Chờ xác nhận',
  da_xac_nhan: 'Đã xác nhận',
  tu_choi: 'Từ chối',
  boi: 'Bởi',
  khong_co_phieu: 'Không có phiếu',
  chuyen_ca_duoc_chap_nhan: 'Yêu cầu chuyển ca được chấp nhận',
  khong_bat_buoc: 'Không bắt buộc',
  thay_doi: 'Thay đổi',
  ban_nhan_duoc: 'Bạn nhận được',
  quyen_truy_cap_cong_viec: 'Quyền truy cập công việc',
  them_nguoi: 'Thêm người',
  nhung_nguoi_truy_cap: 'Những người có quyền truy cập',
  them_nguoi_truy_cap: 'Thêm người truy cập',
  chon_nhan_vien: 'Chọn nhân viên',
  quyen_truy_cap: 'Quyền truy cập',
  chu_so_huu: 'Chủ sở hữu',
  nguoi_chinh_sua: 'Người chỉnh sửa',
  nguoi_xem: 'Người xem',
  xoa_quyen_truy_cap: 'Xoá quyền truy cập',
  nhuong_quyen_so_huu: 'Nhượng quyền sở hưu',
  gop_y: 'Góp ý',
  mo_ta_danh_gia_ho_tro:
    'Vui lòng đánh giá để giúp chất lượng hỗ trợ của Ban Quản Lý Toà Nhà hoàn thiện hơn',
  dang_ky_khach: 'Đăng ký khách',
  lich_su_ra_va: 'Lịch sử ra vào',
  thong_tin_phuong_tien: 'Thông tin phương tiện',
  khach_di_kem_phuong_tien: 'Khách đi kèm phương tiện',
  phuong_thuc_thanh_toan_phi: 'Phương thức thanh toán phí',
  thong_tin_khach: 'Thông tin khách',
  chuong_hinh: 'Chuông hình',
  camera: 'Camera',
  anh_dai_dien_dich_vu: 'Ảnh đại diện dịch vụ',
  thay_nen: 'Thay nền',
  mo_ta_thay_doi_icon: 'Click vào biểu tượng để thay đổi',
  cai_dat_dich_vu: 'Cài đặt dịch vụ',
  tro_lai_de_xuat: 'Trờ lại đề xuất',
  chon_bieu_tuong: 'Chọn biểu tượng',
  bo_cuc: 'Bố cục',
  chia_se: 'Chia sẻ',
  cai_dat: 'Cài đặt',
  camera_an_ninh: 'Camera an ninh',
  nhan_cuoc_goi: 'Nhận cuộc gọi',
  cuoc_goi_nho: 'Cuộc gọi nhỡ',
  khong_nhan_cuoc_goi: 'Không nhận cuộc gọi',
  lich_su_cuoc_goi: 'Lịch sử cuộc gọi',
  chuong_bao: 'Chuông báo',
  goi_loa_ngoai: 'Gọi loa ngoài',
  tu: 'Từ',
  chu_ho_thanh_toan: 'Chủ hộ thanh toán',
  khach_thanh_toan: 'Khách thanh toán',
  khach: 'Khách',
  da: 'Đã',
  ra: 'Ra',
  vao: 'Vào',
  tai: 'Tại',
  ma_qr_khong_hop_le: 'Mã QrCode không hợp lệ',
  thoi_gian_ra_vao_het_han: 'Thông báo thời gian ra vào của bạn đã hết hạn',
  mo: 'Mở',
  the_hinh: 'Thể hình',
  matxa: 'Mát xa',
  boi_loi: 'Bơi',
  cb_loai_xe: 'Vui lòng điền loại xe',
  cb_bien_so_xe: 'Vui lòng điền biển số xe',
  cb_thanh_toan_loai: 'Vui lòng điền phương thức thanh toán',
  cb_dia_diem: 'Vui lòng điền địa điểm',
  cb_thoi_gian: 'Vui lòng điền thời gian',
  cb_thanh_toan_anh: 'Vui lòng điền ảnh đã thanh toán',
  cb_khung_thoi_gian: 'Vui lòng điền khung thời gian',
  cb_ngay_su_dung: 'Vui lòng điền ngày sử dụng',
  cb_cmnd: 'Vui lòng điền chứng minh nhân dân',
  cb_ho_ten: 'Vui lòng điền họ tên',
  cb_sdt: 'Vui lòng điền số điện thoại',
  cb_mat_khau: 'Vui lòng điền mật khẩu',
  cb_mat_khau_cu: 'Vui lòng điền mật khẩu cũ',
  cb_mat_khau_moi: 'Vui lòng điền mật khẩu mới',
  cb_mat_khau_moi_lan2: 'Vui lòng điền lại mật khẩu',
  tb_thanh_cong_dang_ky: 'Đăng ký thành công',
  tb_thanh_cong_xoa: 'Xoá thành công',
  tb_thanh_cong_sua: 'Sửa thành công',
  tb_that_bai_dang_ky: 'Đăng ký thất bại',
  tb_that_bai_xoa: 'Xoá thất bại',
  tb_that_bai_sua: 'Sửa thất bại',
  dang_ky_gym: 'Đăng ký Gym',
  dang_ky: 'Đăng ký',
  hinh_thuc_su_dung: 'Hình thức sử dụng',
  dia_diem: 'địa điểm',
  chon_goi: 'Chọn gói',
  ma_khuyen_mai: 'Mã khuyến mãi',
  gia_theo_dich_vu: 'Giá theo dịch vụ',
  uu_dai: 'Ưu đãi',
  neu_co: 'Nếu có',
  ghi_chu_cho_dich_vu: 'Ghi chú cho dịch vụ',
  lua_chon_hinh_thuc_thanh_toan: 'Lựa chọn hình thức thành toán phù hợp',
  thanh_toan_truc_tiep: 'Thanh toán trực tiếp',
  thanh_toan_online: 'Thanh toán online',
  hd_thanh_toan_tien_ich: 'Quý cư dân vui lòng chọn một dịch vụ để thanh toán',
  ghi_nhan_cong_no: 'Ghi nhận công nợ',
  dinh_kem_hinh_anh_thanh_toan: 'Đính kèm hình ảnh thanh toán',
  chon_loai_ve: 'Chọn loại vé',
  tong_tam_thoi: 'Tổng tạm thời',
  tong_tam_tinh: 'Tổng tạm tính',
  thanh_toan_tai_quay: 'Thanh toán tại quầy',
  dang_ky_boi: 'Đăng ký bơi',
  dang_ky_sauna: 'Đăng ký sauna',
  nuoc_nong: 'Nước nóng',
  phi_nuoc_nong: 'Phí nước nóng',
  tim_kiem_check_list: 'Tìm kiếm theo tên check list',
  cap_nhat: 'Cập nhật',
  tat_cong_viec: 'Tắt công việc',
  vui_long_chon_bo_phan: 'Vui lòng chọn bộ phận',
  thay_doi_thanh_vien: 'Thay đổi thành viên',
  bo_phan_cua_ban: 'Bộ phận của bạn',
  ban_chac_chan_muon_huy: 'Bạn chắc chắn muốn huỷ',
  gui_phan_hoi: 'Gửi phản hồi',
  giao_dich: 'Giao dịch',
  doi_mat_khau: 'Đổi mật khẩu',
  nhap_email: 'Nhập email',
  nhap_sdt: 'Nhập số điện thoại',
  dinh_dang_email_sai: 'Email chưa đúng định dạng',
  dinh_dang_sdt_sai: 'Sdt chưa đúng định dạng',
  khach_hang_duoc_phan_bo: 'Khách hàng được phân bổ',
  cham_soc_khach_hang: 'Chăm sóc kh',
  them_anh_xac_minh_cua_khach: 'Thêm ảnh xác minh của khách',
  tinh_trang_khach_hang: 'Tình trạng khách hàng',
  nguon: 'Nguồn',
  chon_nguon: 'Chọn nguồn',
  so_dien_thoai: 'Số điện thoại',
  ten_goi_nho: 'Tên gợi nhớ',
  anh_xac_minh: 'Ảnh xác minh',
  noi_dung_giai_trinh: 'Nội dung giải trình chi tiết',
  mo_ta_giai_trinh:
    'Đây là thông tin nhân viên vi phạm gửi giải trình cho việc không chăm sóc khách hàng đúng thời gian quy định ',
  thong_tin_giai_trinh: 'Thông tin giải trình',
  khach_hang: 'Khách hàng',
  nhan_vien: 'Nhân viên',
  du_an: 'Dự án',
  chi_tiet_giai_trinh: 'Chi tiết giải trình',
  thong_tin_khach_hang: 'Thông tin khách hàng',
  them_khach_hang: 'Thêm khách hàng',
  cap_nhat_khach_hang: 'Cập nhật khách hàng',
  gui_giai_trinh: 'Gửi giải trình',
  loc: 'Lọc',
  chien_dich: 'Chiến dịch',
  chua_phan_hoi: 'Chưa phản hồi',
  con: 'Còn',
  cua_toi: 'CỦA TÔI',
  da_nhan: 'Đã nhận',
  da_phan_hoi: 'Đã phản hồi',
  danh_sach_vi_pham: 'Danh sách vi phạm',
  giai_trinh: 'Giải trình',
  khach_hang_co_quan_tam_nhung_chua_net:
    'Khách hàng có quan tâm nhưng chưa Net',
  khach_hang_khong_bat_may: 'Khách hàng không bắt máy',
  khach_hang_khong_quan_tam: 'Khách hàng không quan tâm',
  khach_hang_net: 'Khách hàng Net',
  khach_hang_quan_tam: 'Khách hàng quan tâm',
  khach_hang_quan_tam_san_pham_khac: 'Khách hàng quan tâm sản phẩm khác',
  khong_nghe_may: 'Không nghe máy',
  khong_quan_tam: 'Không quan tâm',
  loc_kh_theo_chien_dich: 'Lọc Kh theo chiến dịch',
  loc_khach_hang: 'Lọc khách hàng',
  loc_khach_hang_phan_bo: 'Lọc khách hàng phân bổ',
  loc_khach_hang_theo_chien_dich: 'Lọc khách hàng theo chiến dịch',
  loc_khach_hang_theo_nguon: 'Lọc khách hàng theo nguồn',
  loc_khach_hang_theo_nhom_khach_hang: 'Lọc khách hang theo nhóm khách hàng',
  loc_khach_hang_theo_thoi_gian_tao: 'Lọc khách hàng theo thời gian tạo',
  loc_theo_thoi_gian_phan_bo: 'Lọc theo thời gian phân bổ',
  loc_theo_tinh_trang_vi_pham: 'Lọc theo tình trạng vi phạm',
  loc_theo_nhom_khach_hang: 'Lọc KH theo nhóm khách hàng',
  loc_theo_tinh_trang_khach_hang: ' Lọc KH theo tình trạng khách hàng',
  loc_theo_chien_dich: 'Lọc theo chiến dịch',
  nhan: 'Nhận',
  phan_bo: 'Phân bổ',
  quan_ly_khach_hang: 'Quản lý khách hàng',
  sai_so: 'Sai số',
  sai_so_dien_thoai: 'Sai số điện thoại',
  sale: 'Sale',
  thu_hoi: 'Thu hồi',
  tim_theo_ten_so_dien_thoai_email: 'Tìm theo tên, số điện thoại, email...',
  tu_: 'Từ ',
  vi_pham: 'Vi phạm',
  thong_tin_nhan_vien: 'Thông tin nhân viên',
  vui_long_nhap_dung_dinh_dang_email: 'Vui lòng nhập đúng định dạng email',
  nhap_ma_otp: 'Nhập mã Otp',
  loc_khach_hang_vi_pham: 'Lọc khách hàng vi phạm',
  yeu_cau_huy: 'Yêu cầu hủy',
  thong_ke: 'Thống kê',
  khach_hang_phat_sinh: 'Khách hàng phát sinh',
  yeu_cau_giai_trinh: 'Yêu cầu giải trình',
  giao_dich_dang_xu_ly: 'Giao dịch đang xử lý',
  dang_lien_he: 'Đang liên hệ',
  tiem_nang: 'Tiềm năng',
  dang_cham_soc: 'Đang chăm sóc',
  khong_nhu_cau: 'Đang nhu cầu',
  tiep_can: 'Tiếp cận',
  bieu_do: 'Biểu đồ',
  cong_ty: 'Công ty',
  sale_khai_thac: 'Sale khai thác',
  ty_le: 'Tỷ lệ',
  tong_cong: 'Tổng cộng',
  san_don_vi_kinh_doanh: 'Sàn / đơn vị kinh doanh',
  phong_kinh_doanh: 'Phòng kinh doanh',
  nhom_kinh_doanh: 'Nhóm kinh doanh',
  sau: 'Sau',
  truoc: 'Trước',
  tong_quan_khach_hang: 'Tổng quan khách hàng',
  khach_hang_tiem_nang: 'KH tiềm năng',
  tong_phat_sinh: 'Tổng phát sinh',
  tat_ca_sale: 'Tất cả sale',
  xem_tat_ca: 'Xem tất cả',
  vinh_danh: 'Vinh danh',
};
